### ISSUE TITLE
Accessing current_user from a Datagrid class

### ISSUE THREAD

**Issue by rpassis** [bogdan/datagrid#127]
Hi all,

One of my filters is configured as follows:

```
filter(:template_form, :enum, select: :available_template_forms)
```

And the method definition for `:available_template_forms` is

```
def available_template_forms
    TemplateForm.where(project_id: Project.joins(:users).where(users: {id: current_user.id}))
end
```

I am basically trying to limit the options available in the dropdown based on the current logged in user.

Is it possible to pass an object to the Datagrid class and access it inside the class somehow?

**Comment by PirunSeng** [comment]
I want the same purpose, but it seems doesn't work for me.

My controller:
@client_grid = ClientGrid.new(params[:client_grid].merge(current_user: current_user))

I got this error: "undefined method `merge' for nil:NilClass"

Any help please!
Thanks.

**Comment by bogdan** [comment]
Updated an example to support `nil` correctly.

**Comment by PirunSeng** [comment]
That's cool!
Fixed my problem, thanks.
I wonder if you could explain me what "params.fetch(:the_grid, {})" does.

**Comment by bogdan** [comment]
`params.fetch(:the_grid, {})` == `if params.has_key?(:the_grid) then params[:the_grid] else {} end`

**Comment by PirunSeng** [comment]
Oh, I see.
Thanks very much for this.

**Comment by dwoznicka** [comment]
@bogdan it does not work for me when i try to assign header from a method (need current_user's data in header)

```
class AppointmentsCustomersInvoicesGrid
  include Datagrid

  attr_accessor :current_pro_user

  scope do
    AppointmentsCustomersInvoice.joins(customers: [:detail]).joins(:appointments).joins(:pro_users)
  end

  filter(:customer_name, :string, header: :customer_name_header) do |value|
    self.where("details.firstname LIKE ? OR details.lastname LIKE ?", "%#{value}%", "%#{value}%")
  end

  def customer_name_header
    I18n.t('pro_users.appointments_customers_invoices.index.customer_name', customer_name: current_pro_user.t_customers.capitalize)
  end

end
```

the header is customer_name_header instead of whatever the `customer_name_header` method returns. when i do `header: customer_name_header` (not as symbol), it return an error `undefined local variable or method `created_at_header' for AppointmentsCustomersInvoicesGrid(no filters):Class`

**Comment by bogdan** [comment]
Dynamic headers - the ones generated by method are not supported now. I'll try to find some time next week to implement that.... In the meanwhile, you may try yourself.
