### ISSUE TITLE
How to support features like pipeline operator $match of mongodb?

### ISSUE THREAD

**Issue by xufeiyun** [bogdan/datagrid#139]
In mongodb's aggregation framework, I can easily apply seconds even more times (usually twice) of $match operator to search different records based on master filters, like:
sample1:
	"$match": { segment: {"$in": ["apple", "banana", "orange", "kiwi"]} },
	"$match": { segment: {"$in": ["kiwi"]} }
sample2:
	"$match": { segment: {"$in": ["apple", "banana", "orange", "kiwi"]} },
	"$match": { segment: {"$in": ["apple"]} }

"$match": { segment: {"$in": ["apple", "banana", "orange", "kiwi"]} } means I queried the result, and for the second match, I need to search another word in the returned result. In mongodb these pipeline operator works well, but is it also to do in the datagrid features?

Thanks
Eric

**Comment by bogdan** [comment]
Sorry, but I've never used mongodb myself and I don't know what it's operators mean.

Can you explain a feature you describe what do you expect from datagrid API, like

``` ruby
g = Mygrid.new(segment: ['apple', 'banana'])
g.assets # => ?
```

If you are not familiar with datagrid yet can you explain a feature you would like to build from the end user stand point?
Maybe you have an interface mockup or user story.

**Comment by xufeiyun** [comment]
hmm, I explain it more clearly:
take above sample as example, firstly, I figure out a result by condition like:
g = Mygrid.new(segment: ['apple', 'banana', 'kiwi'])

Then, I should get another two results based on above result, 
one looks like: I find out the records which segment matches 'a'; 
  => maybe something like:  g1 = g.where(segment: "/.*a.*/")
another looks like: I find out the records which segment matches 'w';
  => maybe something like:  g2 = g.where(segment: "/.*w.*/")

That's it.

**Comment by bogdan** [comment]
I  don't know why would you need datagrid to do that. Isn't mongoid enough here (or any other mongo ORM)?

``` ruby
r = Model.where(segment: ['apple', 'banana', 'kiwi'])
r1 = r.where(segment: /.a./)
r2 = r.where(segment: /.w./)
```

If you would like to use datagrid anyway you can do the following:

``` ruby
class Grid
  scope { Model }
  filter(:segment, :string, multiple: true)
  filter(:segment_pattern, :string) do |value, scope|
    scope.where(segment: /#{value}/)
  end
end
```

Based on what you've said, I am not sure you understand what you are doing.

**Comment by xufeiyun** [comment]
Thanks so much.
I'll try it.

The scenario is that I need to search any word in a figured out result(display in a datagrid) and display data in another datagrid. Thus I need parse two conditions for the same field.  My above examples indicates as below meanings: 
(segment equals one of ['apple', 'banana', 'kiwi']) and (segment like '.*a.*') => means search a from the given result
(segment equals one of ['apple', 'banana', 'kiwi']) and (segment like '.*w.*') => means search w from the given result.

Does it make sense?

**Comment by bogdan** [comment]
Yes, makes sense. 

You can do it by creating multiple filters that are filtering the same database field (`segment` in your case) just like in example above:

``` ruby
class Grid
  scope { Model }
  filter(:segment, :string, multiple: true)
  filter(:segment_pattern, :string) do |value, scope|
    scope.where(segment: /#{value}/)
  end
end

grid = Grid.new(segment: ['apple', 'banana'])

subgrid1 = grid.clone.assign_attributes(segment_pattern: '.a.')
subgrid2 = grid.clone.assign_attributes(segment_pattern: '.w.')
```

**Comment by bogdan** [comment]
Hope you got what you want. Comment if not
