### ISSUE TITLE
highlight some rows based on column value

### ISSUE THREAD

**Issue by amit-siddhu** [bogdan/datagrid#141]
Hi Bogdan,
                Is there any functionality in Datagrid to highlight rows on the basis of column value.
e.g. I have a column (boolean) in database , now i want to highlight all rows (different color) for which the column value is 'true'. Also i don't want to display that column in the datagrid table just want to highlight that row.

Thanks

**Comment by bogdan** [comment]
You would need to modify datagrid built-in partials to do it.
First run: `rake datagrid:copy_partials`.
It will bring builtin partials under your control and you can modify and commit them.

Modify the `_row.html.erb` partial:

``` diff
-<tr class="<%= options[:cycle] && cycle(*options[:cycle]) %>">
+<tr class="<%= options[:cycle] && cycle(*options[:cycle]) %> <%= grid.respond_to?(:column_class) ? grid.column_class(asset) : "" %>">
   <% grid.html_columns(*options[:columns]).each do |column| %>
     <td class="<%= datagrid_column_classes(grid, column) %>"><%= datagrid_value(grid, column, asset) %></td>
   <% end %>
```

Now any grid supports the configuration like this:

``` ruby
class IssuesGrid

  scope { Issue }

  def column_class(issue)
    case issue.status
    when "fixed" then "green"
    when "rejected" then "red"
    else "blue"
    end
  end
end
```

**Comment by amit-siddhu** [comment]
Many thanks Bogdan!!
