### ISSUE TITLE
Accessing current_user from filter with a lambda to select columns for display

### ISSUE THREAD

**Issue by cmcguff** [bogdan/datagrid#142]
Variant on #127 

I can get this displaying a list where I can filter on a current_user method the way I want, but how do I select the columns for display? This is done elsewhere with a lambda but I can't get this to work here.

Working code without lambda:

    filter(:user_id, :enum, select: :available_users, multiple: true, include_blank: false) do |value|
        self.where(:users => {:id => value})
    end
    def available_users
        User.where(id: current_user.me_and_reports)
    end

If I try and apply the other approach here and do something like this:

    def available_users
        lambda {current_user.me_and_reports.all.map {|u| ["#{u.first_name} #{u.last_name}", u.id]}}
    end

I get an error:

    undefined method `empty?' for #<Proc:0x007f96fb3de408>

Is there a better way I can select the columns to be displayed in the select in this case?

**Comment by bogdan** [comment]
Second example should not work because extra proc is not needed - method can work as proc already.

I don't see why first sample doesn't work. Is there any exception or it doesn't work as expected?

**Comment by cmcguff** [comment]
First one is not erroring but gives me a list of the user object id's not the pretty formatted list of user names from the lambda option.

**Comment by parinha** [comment]
Hi!
I'm new to datagrid.

Is it possible to set the default attribute as dynamic?

attr_accessor :current_user
filter(:user_id, :enum, select: :available_users, default: :current_login_user, multiple: true, include_blank: false)

def available_users
    User.where(id: user_id).map { |u| [u.name, u.id] }
end

def current_login_user
    User.where(id: current_user).map { |u| [u.name, u.id] }
end

**Comment by bogdan** [comment]
No, dynamic default depends on the order of attributes assignment. You need to control that manually.

Easy version:

``` ruby
class Controller
  def index
    @grid = Grid.new(params[:grid].reverse_merge(current_user: current_user, user_id: current_user.id)
  end
end
```

Hard advanced version (required if grid class is reused multiple times):

``` ruby
def initialize(attributes = nil)
  super(attributes)
  if current_user && !attributes[:user_id]
    self.user_id = current_user.id
  end
end
```

**Comment by parinha** [comment]
@bogdan work like a charm 👍 you saved my day. Thanks
```
def index
    @marker_grid = MarkersGrid.new(params.fetch(:markers_grid, {}).merge(current_user: current_user, user_id: current_user.id)) do |scope|
      scope.page(params[:page])
    end
    @marker_grid.assets
end
```

**Comment by bogdan** [comment]
You need to change `merge` to `reverse_merge` because you can not change the default value now.

**Comment by parinha** [comment]
@bogdan you're right. I have put reverse_merge and its working now 👍 
```
def index
    @marker_grid = MarkersGrid.new(params.fetch(:markers_grid, {}). reverse_merge(current_user: current_user, user_id: current_user.id)) do |scope|
      scope.page(params[:page])
    end
    @marker_grid.assets
end
```

**Comment by parinha** [comment]
@bogdan currently, i have figured out that its always filtered by current_user. So is there a way to filter all data without current_user?

**Comment by bogdan** [comment]
Try this:

``` ruby
    @marker_grid = MarkersGrid.new(params.fetch(:markers_grid, {current_user: current_user, user_id: current_user.id})) do |scope|
```

**Comment by parinha** [comment]
its working now. thanks man :)
