### ISSUE TITLE
Columns and Filters using param_name and not I18n-key when looking up translations

### ISSUE THREAD

**Issue by olejrosendahl** [bogdan/datagrid#143]
Hi @bogdan,

I'm using inheritance on some of my grids and ran into some issues with my translations when overriding Datagrid::ActiveModel.param_name. Maybe translation lookups should use ActiveModel's i18n_key to look up the translations instead of Datagrid::ActiveModel.param_name?

Thanks a lot for this gem btw, it's been a huge help.

**Comment by bogdan** [comment]
Agree, it should be different from `param_name` and `i18n_key` could be a good candidate. Sad design issue. We also need to support backward compatibility with deprecation warning if possible.

I am currently on vacation, not sure if I will find time for it in next 2 weeks. If you want to get patch quicker, you may submit a PR.

**Comment by olejrosendahl** [comment]
Ok, great. I've made a fork, will submit a PR as soon as I've fixed the deprecation warning. Enjoy your vacation!
