### ISSUE TITLE
Dynamic columns and proc ordering not working

### ISSUE THREAD

**Issue by apetrov88** [bogdan/datagrid#145]
I made some dynamic columns which work fine, but when I tried to make the ordering I always got the exception that the column was missing. Which actually is normal becasue at that time columns_array is empty. I manage to overcome it by commenting the the exception raising, but thats not a good option.

**Comment by bogdan** [comment]
I've fixed an issue in master by moving order value validation code to the place where order is applied - `#assets` method. It should fix the issue, but I am not yet sure this is the best approach. I'll think about it for some time and than make a release if will not find a better solution.

**Comment by bogdan** [comment]
Fixed in 1.3.7
