### ISSUE TITLE
Is it possible to have more than one grid on the same page?

### ISSUE THREAD

**Issue by catogonzalez** [bogdan/datagrid#147]
That is, two grids each with its own scope, definition, filters, columns, etc.

**Comment by catogonzalez** [comment]
Yeah, pretty simple. Sorry for the dumb question.

**Comment by bogdan** [comment]
As I understand the classes for two grids need to be different.
Sure, you just have two grid classes and instantiate them in controller:

``` ruby
def index
  @grid1 = Grid1.new(params[:grid1]) { ... }
  @grid2 = Grid2.new(params[:grid2]) { ... }
end
``` 

Form with filters from both grids will be a little tricky:

``` haml
= form_for @grid1, url: "..." do |g1|
  = fields_for @grid2 do |g2|
    - @grid1.filters.each do |filter|
      = g1.datagrid_label filter
      = g1.datagrid_filter filter
  - @grid2.filters.each do |filter|
      = g2.datagrid_label filter
      = g2.datagrid_filter filter
```

In case grids will have same class you would need to use `as: 'grid1'` option for `form_for` to split parameters into two separated hashes.

Table display should not be a problem:

``` haml
= datagrid_table @grid1
= datagrid_table @grid2
```

**Comment by catogonzalez** [comment]
This is just what I needed @bogdan. You have done a great job. Thanks!
