### ISSUE TITLE
How to apply custom css to the grid?

### ISSUE THREAD

**Issue by catogonzalez** [bogdan/datagrid#148]
I made a copy of datagrid.css.sass from the gem folder to app/assets/stylesheets but changes to that file don't seem to work. What would be the best approach to customize the styles of the datagrid?

**Comment by bogdan** [comment]
Try to stop the server, run `rake tmp:cache:clear` and start it again.

**Comment by catogonzalez** [comment]
Worked perfectly. Didn't know about that trick. Thanks a lot!
