### ISSUE TITLE
Rename SASS files (Rails deprecation warning)

### ISSUE THREAD

**Issue by dziemba** [bogdan/datagrid#149]
Rails 4.2.1 prints deprecations warnings:

```
DEPRECATION WARNING: Extra .css in SASS file is unnecessary. 
Rename [...]/gems/datagrid-1.3.7/app/assets/stylesheets/datagrid.css.sass 
to [...]/gems/datagrid-1.3.7/app/assets/stylesheets/datagrid.sass.
```

**Comment by bogdan** [comment]
Are you sure it will work on previous versions of rails as well?

**Comment by dziemba** [comment]
Yes, it should be fine. 

The oldest Rails version the gem supports seems to be 3.2.18 (according to Gemfile), which would allow for sass-rails 3.2.6.
According to https://github.com/rails/sass-rails/blob/v3.2.6/lib/sass/rails/importer.rb#L12
that versions accepts both `.css.sass` and `.sass` files. 

Support for `.css.sass` was removed in sass-rails 5 via https://github.com/rails/sass-rails/pull/271 and https://github.com/rails/sass-rails/pull/291

**Comment by dziemba** [comment]
I saw that you fixed this on master and already committed a version bump. Can you also release the new version as a gem? Thanks!

**Comment by bogdan** [comment]
Enjoy 1.3.9.
