### ISSUE TITLE
Filter not being applied

### ISSUE THREAD

**Issue by Nevtep** [bogdan/datagrid#150]
Hello, I have a report that has a scope using a join between user and compliance model (user has one compliance)

the report uses a filter for the users.created_at field, like this:

    filter(:created_at, :date, :range => true, :header => 'Registration Date')

however the filter is not getting applied, I get all records no mater  the value I enter, I checked the SQL and the where clause is not evenm added, also tryed like this:

    filter(:registrastion, :date, :range => true, :header => 'Registration Date') do |value|
        where("users.created_at >= '#{value[0]}' and users.created_at <= '#{value[1]}'")
    end

My reports that don't have a join work without problems, any ideas why this is happening or how should I create the filter?

Thanks!

**Comment by bogdan** [comment]
I am not sure why. Lets do some debugging in console:

``` ruby
grid = GridClass.new(registration: ['2015-01-01', Date.today])
grid.assets.to_sql # => ?
```

What is the output for you?

**Comment by Nevtep** [comment]
Thank you for your response, I did as you said and got the correct sql, turns out that I was using wrong params for the report creation, I had:

    @report = "UsersByCountry#{@period}Report".constantize.new(params[:users_by_countryreport])

and it should been:

    @report = "UsersByCountry#{@period}Report".constantize.new(params[:users_by_country_report])

I fixed that and now it works.

Thanks!
