### ISSUE TITLE
Is there also a way to use an if... else... on a filter

### ISSUE THREAD

**Issue by Nickk4** [bogdan/datagrid#152]
For a column it's possible to specify when to include that column. Is this also possible for a filter? (http://stackoverflow.com/questions/30510558/how-to-include-a-datagrid-filter-only-if-certain-conditions-are-met)

**Comment by bogdan** [comment]
This is not currently possible. I think this is a right feature to have. You will do it soon or you can submit a PR if you don't want to wait.
