### ISSUE TITLE
Row selection

### ISSUE THREAD

**Issue by spiffistan** [bogdan/datagrid#153]
Is it possible to add a checkbox at the start of each row to facilitate row selection?

I've tried a hacky solution, but I'd like to not have a column name for that specific column...

**Comment by bogdan** [comment]
Why you can't use blank header?

``` ruby
column(:checkbox, header: '', html: true) do |model|
  check_box_tag(:row_selection, model.id)
end
```

**Comment by spiffistan** [comment]
I hadn't realized you could set the header, thanks!
