### ISSUE TITLE
how sort custom column

### ISSUE THREAD

**Issue by rperez2013** [bogdan/datagrid#155]
hi!, i have this problem: i can't implement sort for the columns total and total2, when i am grouping data

the query:
scope do 
    Model.select("Model.column1,sum(Model.column2) as total, sum(Model.column3) as total2").group(:column1)
end
the columns:

column(:total,:mandatory=>true,:order=>'total')
column(:total2,:mandatory=>true,:order=>'total2')

sorry for my english.

**Comment by bogdan** [comment]
What is the problem? Do you get any exception message? What do you suppose to get instead of what you are getting?

Can you solve the problem in plain SQL? Does the following gives you a properly sorted result?

``` sql
select column1 as total, sum(column2) as total2, sum(column3) as total3 from models group by column1 order by total
```

**Comment by rperez2013** [comment]
i want implement sort like 
http://datagrid.herokuapp.com/time_entry_reports

but i want sort for the column hours ( the grouped value) like the others values (with up arrow and down arrow)

so, when i click on a up arrow or a down arrow, the mesagge error is:
PG::UndefinedColumn: ERROR:  column "total" does not exist


because in the query generate, in the select the column total no appear, but in the order by appear. really this adds an extra column: SELECT COUNT(*) AS count_all,

**Comment by bogdan** [comment]
That is kind of postgresql problem that you can no order by an aliased column. You have to do the following:

``` ruby
column(:total,:mandatory=>true,:order=>'sum(column2)')
column(:total2,:mandatory=>true,:order=>'sum(column3)')
```

**Comment by rperez2013** [comment]
thank's you very much!!! :DD
