### ISSUE TITLE
Sorting columns with unpersisted data

### ISSUE THREAD

**Issue by fender053** [bogdan/datagrid#156]
I have two columns of calculated data that display just fine when the grid is first pulled up and when additional columns are selected. When clicking the arrows to sort any column, the values in the calculated columns disappear.

Grid code:
```
class TheGrid
  include Datagrid
  
  filter(:project_sponsor)
  filter(:required, :xboolean)

  column_names_filter(:header => "Extra Columns", checkboxes: true)
  column(:name, :mandatory => true) do |lmp|
    lmp.project.name
  end
  column(:project_sponsor, :mandatory => true) do |lmp|
    lmp.project.sponsor
  end
  column(:required, :mandatory => true)
  column(:over_budget, mandatory: true) #unpersisted, calculated value
  column(:resource_conflict, mandatory: true) #unpersisted, calculated value

end
```
Any suggestions?

**Comment by bogdan** [comment]
What do you mean by "columns of calculated data"? Is it calculated in a model via method or they are calculated on model `save` in a callback etc?

If you have sorting arrows on a column without specifying `order` option, it means that there are columns like that in your database I suppose. And when you sort by them it just brings all nulls on top.
So there are models where these columns are null in your DB. 

How do you suppose to sort by un-persisted value? You can do it, but only in case you are 100% sure that number of records displayed by grid will never be more then 10k.

You can switch from `ActiveRecord` to `Array` in a scope:


``` ruby
scope { Model.what_ever_scope.to_a }
```

It `Model#over_budget` and `#resource_conflict` exist, there will be not problem sorting by them in ruby.

**Comment by fender053** [comment]
Apologies for not being clearer with my question.
There will likely never be more than 100 records for my grid. Using rails 4.2.3
My two unpersisted values are calculated via a model method. The method adds a boolean attribute.

```
class Model < ActiveRecord::Base
  attr_accessor :over_budget
  
  def check_budget
    if some logic
      self.over_budget = true
    else
      self.over_budget = false
  end   
end
```
In my controller I am setting the scope of the grid:
```
def index
  @models = Model.where(map_id: params[:map_id])
  @models.check_budget
  @grid = TheGrid.new( params[:the_grid] ) do |scope|
    @models
  end
end #index
```
When the index page is first loaded the true or false value appears in the over_budget column. If I select an optional column to add and reload the page, the true or false value stays in the over_budget column. The problem occurs if I sort by any column (persisted or not), `risk_score` as an example. When doing this, the true or false values in the over_budget column disappear all together. Perhaps it reverts back to the default scope set in the grid file where the `check_budget` method hasn't been called?
```
column(:risk_score, header: "Risk score")
```
I changed the scope in the controller as suggested:
```
@grid = TheGrid.new( params[:the_grid] ) do |scope|
  @models.to_a
end
```
I then receive undefined method `reorder' for #<Array:0x007fc11e5291d0> when attempting to sort by any column (persisted or not).
trace:
```
datagrid (1.3.9) lib/datagrid/drivers/active_record.rb:51:in `desc'
datagrid (1.3.9) lib/datagrid/ordering.rb:110:in `apply_desc_order'
datagrid (1.3.9) lib/datagrid/ordering.rb:79:in `apply_order'
datagrid (1.3.9) lib/datagrid/ordering.rb:43:in `assets'
datagrid (1.3.9) lib/datagrid/renderer.rb:44:in `table'
datagrid (1.3.9) lib/datagrid/helper.rb:42:in `datagrid_table'
app/views/project_priority_reports/index.html.erb:3:in `_app_views_project_priority_reports_index_html_erb__1127511513021308732_70233534653440'
```
Just looking for a way to keep the calculated boolean value displayed when sorting by any column.

**Comment by bogdan** [comment]
scope type in class should match defined in controller. Change scope in grid class to let it understand you gonna work with array but not active record:

``` ruby
scope { [] }
```

**Comment by fender053** [comment]
Thanks! That stopped the undefined method `reorder' for #Array:0x007fc11e5291d0

Now that the column data is staying, is there any way to sort by a value calculated in the column definition? I am running a method in the column definition to calculate a numerical value. Can I set the order option in the column block after this value is calculated?
```
@grid.column(:roi) do |lmp|
  bc = lmp.project.find_main_bc
  (bc.nil? or lmp.over_budget == true)  ? "N/A" : BusinessCase.calculate_roi(@project_cash_flows[bc.id.to_s])
end #roi
```
I would like to sort by the value returned by the calculate_roi method if possible.  If not, I can perform this calculation and place the number in the array before passing it to DataGrid as the scope.

Thank you.

**Comment by bogdan** [comment]
Better to do calculations in model then in grid.
Also you need to split formatting from data.

``` ruby
class Model

  def roi
      bc = lmp.project.find_main_bc
     (bc.nil? or lmp.over_budget == true)  ? nil : 
        BusinessCase.calculate_roi(@project_cash_flows[bc.id.to_s])
  end
end

@grid.column(:roi) do |lmp|
  format(lmp.roi) do |value|
    value ? value : "N/A"
  end
end
```

**Comment by fender053** [comment]
Thanks for all of the help! Also, thank you for all of the work on the gem.
