### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by PBM42** [bogdan/datagrid#161]
Hi,
Where is the best place to do the Datagrid config ? It should benefit the I18n date format.
Thanks!

**Comment by PBM42** [comment]
Yeah, I try this but Rails app instantly exit : 
```ruby
/config/initializers/datagrid.rb:11:in `block in <top (required)>': undefined method `datetime_formats=' for #<Datagrid::Configuration:0x007f46cd5fdfa0> (NoMethodError)
```

**Comment by bogdan** [comment]
You can be wrong in the configuration file or your datagrid version can be too small.
Can you show what you've written there and your datagrid version?

**Comment by PBM42** [comment]
I just copy past from the wiki, so it must be the datagrid version (1.0.3)...
If I only keep config.date_formats, it works

**Comment by bogdan** [comment]
Date Time support was added at version 1.0.4. You you need to upgrade or use only date.
https://github.com/bogdan/datagrid/commit/aebcea89e9fcfd183a5b103de6a1c68cfd720564
