### ISSUE TITLE
Boolean filter with default true fails

### ISSUE THREAD

**Issue by guzart** [bogdan/datagrid#162]
I have the following filter definition

    filter(:hide_archived, :boolean, default: true) do |value, scope| 
        value.to_bool ? scope.current : scope
    end

But the value is always true. I think this is because my default is set to true and the checkbox options are set not to include the hidden input that sets the default to false.

https://github.com/bogdan/datagrid/blob/d3cb22b85f5c6c132fd9cb5399271b0361a164ec/lib/datagrid/form_builder.rb#L23

I solved the issue by using a custom form partial and pass the option `include_hidden: true` to the `f.datagrid_filter filter` method.

Thank you for an awesome gem.

**Comment by bogdan** [comment]
You are right. hidden input should be in place when default set to `true`. Thanks.
