### ISSUE TITLE
Running a filter by default

### ISSUE THREAD

**Issue by LimeBlast** [bogdan/datagrid#163]
I've created a filter which looks like the following:

    filter(:transaction_type_unit_of_measure_type, :enum,
           header:        'Transaction Type',
           include_blank: false,
           select:        [['Voice', 0], ['Data', 1], ['SMS', 2]]) do |value|
      self.where(transaction_type_unit_of_measure_type: value)
    end

...and it seems to do what I need upon submission of the form.

My issue is I need one of them (preferably 'Voice') to be run by default on page load, without needing to have run the search box.

How can I achieve this? Thank you.

**Comment by bogdan** [comment]
Add 'default: 0' option and that is it

**Comment by LimeBlast** [comment]
That's amazing, thank you so much.
