### ISSUE TITLE
CSV file exported got unreadable Unicode characters

### ISSUE THREAD

**Issue by PirunSeng** [bogdan/datagrid#167]
I have some data which are Unicode characters. I got a problem when I export the data. The thing is that Unicode characters become unreadable.
Any help please!
Thanks,

**Comment by bogdan** [comment]
Try to use plain ruby to export that type of data into CSV like in example here:
http://stackoverflow.com/questions/4822422/output-array-to-csv-in-ruby

Is it readable?

**Comment by PirunSeng** [comment]
Thanks, I'll try, and let you know whether or not it can help.
