### ISSUE TITLE
Is there a way to choose any fields (columns) to be displayed?

### ISSUE THREAD

**Issue by PirunSeng** [bogdan/datagrid#168]
I'm think of ability to choose any fields to be displayed on the view, and then I can still do filtering or ordering as usual.

I've built a new form in which I can post some params and get them as column_names by following the Columns Visibility section. This works well by showing only columns I need, but the problem is the filtered params were gone.

I wonder if there is a way I can do something like:
1. Choose fields (columns) to be displayed
2. Filter
or Filter then choose the fields later.

Hope there is a way.
Thanks.

**Comment by PirunSeng** [comment]
I luckily solved this after looking around back and forth the Demo app, Front End, and Columns wiki.

I've solved it by modifying built-in partial.
I've added check boxes inside the form. Everything works as expected.

In short, filters and check fields (columns) to be displayed are in only one form.

**Comment by bogdan** [comment]
You are becoming a true datagrid ninja :+1:

**Comment by PirunSeng** [comment]
I'm sorry to reopen this issue because I've just found something unpleasant.
Choosing columns and filtering data work just fine, but there is a problem with "sorting".

When I click the sort order, it seems like it removes the custom form elements (checkboxes) from the params.

+ This works well with check boxes and filtering:
`{
 "name_"=>"name",
 "client_grid"=>
  {"name"=>"pirun",
   "gender"=>"male",
   },
 "commit"=>"Search",
 "controller"=>"clients",
 "action"=>"index"}`

+ This sort order has removed custom elements params ("name_"=>"name") in my case:
`{
"client_grid"=>
  {
  "gender"=>"male",
  "name"=>"pirun",
  "descending"=>"true"
   },
 "locale"=>"en",
 "controller"=>"clients",
 "action"=>"index"
 }`

I don't know if this can help you understand. Anymore concern, please let me know.
Thanks,

**Comment by PirunSeng** [comment]
Hi @bogdan !
I'm here again and to close this issue again :D

I've come up with an idea. Why don't I check the "_order_for.html.haml" partial in the case related to the ordering?
I just merged the params with the grid params. The problem solved.

Original generated partial:
`= link_to(I18n.t('datagrid.table.order.asc').html_safe, url_for(grid.param_name => grid.as_query.merge(order: column.name, descending: false)), class: 'asc')
-  = link_to(I18n.t('datagrid.table.order.desc').html_safe, url_for(grid.param_name => grid.as_query.merge(order: column.name, descending: true )), class: 'desc')`

How I merge the params:
`= link_to(I18n.t('datagrid.table.order.asc').html_safe, url_for(params.merge(grid.param_name => grid.as_query.merge(order: column.name, descending: false ))), class: 'asc')
  = link_to(I18n.t('datagrid.table.order.desc').html_safe, url_for(params.merge(grid.param_name => grid.as_query.merge(order: column.name, descending: true ))), class: 'desc')`

Thanks for such this customizable gem. I really like it.
@bogdan ! You're awesome!

**Comment by bogdan** [comment]
Yes, merge like that can be insecure and you may reveal controller and action name to the end user. This is not a critical security problem, but still...

You need to merge only params that need to persist between requests: `params.slice(:a, :b)` instead of all of them.

**Comment by PirunSeng** [comment]
It sounds not really good to me that it can cause insecure even if it is not critical.
I'm afraid I don't know how to follow your advice.
May you write me the full syntax please?

**Comment by bogdan** [comment]
If you just need the `_name` parameter do this:

``` haml
= link_to(I18n.t('datagrid.table.order.asc').html_safe, url_for(grid.param_name => 
    grid.as_query.merge(order: column.name, descending: false, :name_ => params[:name_] )
   ), class: 'asc') 
= link_to(I18n.t('datagrid.table.order.desc').html_safe, url_for(grid.param_name => 
    grid.as_query.merge(order: column.name, descending: true, :name_ => params[:name_] )
  ), class: 'desc')
```

**Comment by PirunSeng** [comment]
It would look better if I had only a few parameters.
In my case, I have almost 30 parameters (name_, gender_, dob_, etc.)

Still I should do that, or you can suggest me another way?

**Comment by bogdan** [comment]
It is really crazy that you have that many. You must be doing something wrong.
E.g. you can put those in a `session` but not in `params`: http://guides.rubyonrails.org/action_controller_overview.html#accessing-the-session

**Comment by PirunSeng** [comment]
I think so.
Like I told you, I'm a beginner. Getting things work is fine enough for me for now.
I haven't worked with session yet since I started.
I really need to learn more than that.
Thanks,
