### ISSUE TITLE
Add extra ?locale=en parameter to filter form

### ISSUE THREAD

**Issue by kalbunna** [bogdan/datagrid#170]
Hello,

There is a ways to add extra parameter to URL when search form is submitted?

Thank you in advance!

**Comment by kalbunna** [comment]
I have solve the problem by using:

```
def set_locale
    I18n.locale = params[:locale] || I18n.locale || I18n.default_locale
  end
```
As datagrid always clear params[:locale] and it set I18n.locale itself.

**Comment by bogdan** [comment]
You can modify built-in partial `datagrid/_form` to add a hidden field to all datagrid forms:

``` haml
= hidden_field_tag :locale, I18n.locale
```

More advanced advice:

I would recommend you make a locale param part of a route but not a GET param with routes like:

```
scope "(/locale/:locale)" do
  resources :whatever
  ...
end
```

In this way, it will be easier to maintain `:locale` as parameter accross the app.
