### ISSUE TITLE
When I'm use scaffold, generator don't put CRUD def in controller, or delete if them exits. This is error? How rigth use scaffoldin?

### ISSUE THREAD

**Issue by schekin** [bogdan/datagrid#172]
When I'm use scaffold, generator don't put CRUD def in controller, or delete if them exits. This is error? How rigth use scaffoldin?

**Comment by bogdan** [comment]
Yes, scaffold overwrites the entire controller. You may copy the `index`

**Comment by bogdan** [comment]
Fixed.
