### ISSUE TITLE
Filter parameter 'grid' is unused in scope

### ISSUE THREAD

**Issue by diegoslice** [bogdan/datagrid#173]
Hi,

I have two form filters, a combo box (categories) and a check box (subs) to include sub categories. When I use code like the following my IDE (RubyMine 8) compains that 'grid' is unused in scope and grid.subs never has a value as a result. 

```
filter(:category_id, :enum,
       :select => lambda {Category.all.order(sort_order: :asc).map {|c| [c.formatted_name, c.id]}},
       :multiple => false,
       :include_blank => false,
       :header => "Category"
  ) do |value, scope, grid|   # <= This is where RubyMine complains that grid is never used in scope
      if value != 1 then     # 1 is 'All' in the combo box so skip whenever ==1
        if grid.subs ==1 then     # 1 means the sub category check box is checked
           scope.where("cars.category_id = " + value + " or cars.subcategory_id = " + value)
        else
          scope.where("cars.category_id = " + value)
        end
      end
end
```

I'm basically trying to access the grid.subs checkbox when determining the correct scope of the category combo box filter. This is being tested with Datagrid 1.4.2. Thanks!

**Comment by bogdan** [comment]
How the sub is defined? Is the ide warning the only one complaint?

**Comment by bogdan** [comment]
Are you sure the datagrid version is modern enough? This is the only guess I have.

**Comment by bogdan** [comment]
I hope you have fixed your issue. Closing... Comment if require any more help.
