### ISSUE TITLE
order column with calculated data

### ISSUE THREAD

**Issue by dantete** [bogdan/datagrid#177]
Hi! 

I can´t order a column with already calculated data. The origin of calculated data is the difference between 2 columns (type datetime)

Model: Request
-accepted_request (datetime)
-finished_request  (datetime)
- finished_request - accepted_request = duration_request

**model_grid.rb:** 
column(:duration_request, :header => "Duration", :mandatory => true) do |req|
     (req.accepted_request.nil? or req.finished_request.nil?) ? 
     "---" : Time.at(req.finished_request - req.accepted_request).utc.strftime("%H:%M:%S")
 end

The view is OK, i saw the header and row info with format: 00:00:23.
any hint o solution? thanks!

**Comment by bogdan** [comment]
You should use an SQL to do that in general case.
It depends on DB but all of them allow to do that.
Mysql one: https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_datediff

When you will learn how to do it in SQL, you may put  those as 

``` ruby
column(:duration_request, order: "<SQL>", order_desc: "<SQL> DESC")
```

Ensure you specify both `order` and `order_desc` because not all SQL order statements can be reversed automatically.

**Comment by dantete** [comment]
i´m using postgresql. i Wrote this query by command line:

select (requests.accepted_request  - requests.finished_request) as c1 from requests order by c1 ASC;
        c1
------------------
 -00:02:35.845565
 -00:01:12.515345
 -00:01:01.628982
 -00:00:50.607988
 -00:00:24.091667
 -00:00:23.716335
 -00:00:13.006128
 -00:00:12.650934


















(26 rows)
________________________________
All good, But i tested the hint and got error: 

**requests_grid.rb: **
`column(:duration_request, order: "<SQL>", order_desc: "<SQL> DESC")`
 i replaced  <SQL> with my exact query and variations, but i got: 
"undefined method `duration_request' for #<Request:0x007fd2cdbf9198>"

i tested change column(**:duration_request**..... by **column(:c1**.... and i got the same error.

- am i replacing badly the query in "<SQL>" ?
- what part of my query must i replace for <SQL> in order: and order_desc: ?

**Comment by bogdan** [comment]
You don't have to remove the column block to calculate and format the value for HTML table.
I just skipped it in the example because this is not what doesn't work.

Try this:

``` ruby
ORDER = "(requests.finnished_at - requests.accepted_at)"
column(:duration_request, order: ORDER, order_desc: "#{ORDER} DESC") do |req|
  (req.accepted_request.nil? or req.finished_request.nil?) ? 
    "---" : Time.at(req.finished_request - req.accepted_request).utc.strftime("%H:%M:%S")
end
```

**Comment by dantete** [comment]
@bogdan !  it works! 
i searched in closed issues but i found nothing.
thank you very much for the help and the Gem! 👍 

i have a last question. In Issue [https://github.com/bogdan/datagrid/issues/156](url) you wrote: 

> How do you suppose to sort by un-persisted value? You can do it, but only in case you are 100% sure that number of records displayed by grid will never be more then 10k.

i dont understand completely it you want to say. 
can i in my case display more than 10K ??
