### ISSUE TITLE
export to XLS

### ISSUE THREAD

**Issue by dantete** [bogdan/datagrid#178]
Hi. 

how do you export to XLS? 
I searched in the wiki and closed issues but i found nothing. 

i already tested with Nokogiri getting the html table. 
and i tested with: send_data @grid.to_xls xD 
but nothing... 

any hint or solution?? thanks!

**Comment by bogdan** [comment]
You can export to CSV and open the file with XLS. This is what most people do. I can put up and XLS example for you if you want, but it should be super simple.

Use the `to_csv` function from source code as an example and just replace CSV library calls to XLS library calls:

``` ruby
      def to_csv(*column_names)
        options = column_names.extract_options!
        csv_class.generate(
          {:headers => self.header(*column_names), :write_headers => true}.merge!(options)
        ) do |csv|
          each_with_batches do |asset|
            csv << row_for(asset, *column_names)
          end
        end
      end
```

**Comment by dantete** [comment]
when i open the .csv with Excel in Mac osx 10.11 alert message is showed: 

> Microsoft Excel cannot access the file 'xx/xxx/xxxx/file.csv'.
> There are several possible reasons:
> 
> • The file name or path name does not exist.
> • The file you're trying to open is being used by another program. Close the document in the other program, and try again.
> • The name of the workbook you're trying to save is the same as the name of another document that is read-only. Try saving the workbook with a different name.
> 

**in mac: **
i am opening the .csv files with Numbers in MAC.
i changed permissions of file a chmod 777 and Excel show the same message.

**in Ubuntu: **
i can view and modify the .csv with libre office.

i will do that you wrote me.

**Comment by bogdan** [comment]
Are you able to open `.xls` documents on mac? Are you able to open CSV file from other source than datagrid? E.g. You can search for csv file in the internet, download it and try to open. Also what would happen if you save a file in CSV format from Excel itself and open it again. Also just google for your problem....

**Comment by dantete** [comment]
-i am able to open .xls documents in Mac with M. Excel. 
-i am able to open csv files from other sources. 
-i am able to open un saved cvs file exported with excel.    

don´t worry.
thanks!

**Comment by bogdan** [comment]
can you send the CSV you can not open? You may reduce dataset to one record with filters if you scare about data disclosure.

**Comment by dantete** [comment]
@bogdan 
now i can open exported .csv files with excel. 

The problem was the name folder and path where i was exporting .csv files. 
the problematic path is: "/Users/myuser/Desktop/aux/filexxx.csv", where "aux" in "Desktop" was the problem. 

in any other path i can open the .csv files with excel.

**Comment by bogdan** [comment]
LoL, you should report a bug to microsoft.
