### ISSUE TITLE
Activable (pre-set) filters ?

### ISSUE THREAD

**Issue by mclak** [bogdan/datagrid#180]
Hi, 
Is there a way to hide filters with a default value (and not take them into consideration), until a button (or a link) that "activate" them is clicked ?

What I need is, for example, to filter only the elements of the grid that were updated in the past 24h or the past week. To do that I saw the range option in the date filters, but I think it would be better for the user if he didn't have to type the dates by himself, and just click somewhere that says "Past 24h" , "Past week" or "All time".

If you could point me in the right direction, that would be a really big help !
Thanks in advance

**Comment by bogdan** [comment]
Filter should reflect the UI but not the implementation - if you want user to choose from preselected options, you should use the `enum` filter:

``` ruby
filter(:date_period, :enum, select: [["Past 24 hours", "24_hours"], ["Past Week", "past_week"]]) do |value, scope|
  scope.where(created_at: 
  case value
  when "24_hours"
    [24.hours.ago, Time.now]
  when "past_week"
    [1.week.ago.beginning_of_week, 1.week.ago.end_of_week]
  end
  )
end
```

**Comment by mclak** [comment]
Alright, I'm gonna follow your advice then, enum it is ! 
Thank you for the quick response.
