### ISSUE TITLE
where  add bootstrap class to div table?

### ISSUE THREAD

**Issue by schekin** [bogdan/datagrid#184]
where  add bootstrap class to div table?

**Comment by bogdan** [comment]
You mean tag `<table>` right? There is no table `<div>`.

See this section of a wiki: https://github.com/bogdan/datagrid/wiki/Frontend#modifying-built-in-partials

**Comment by pjforde1978** [comment]
@schekin I don't know why @bogdan didn't just answer your question... less effort. :)

In your index.html.erb:

`<%= datagrid_table @grid, html: {:class => "datagrid users_grid table"} %>`

Note that for my UsersGrid, the class on the table was already set to "datagrid users_grid". I added table for Bootstrap 4 support.
