### ISSUE TITLE
Accessing current_user from a Datagrid class revisited

### ISSUE THREAD

**Issue by flexloop** [bogdan/datagrid#187]
Hi All-

I am trying to use current_user from devise to filter a datagrid. I am using the response to issue #127 as a guide but I am getting  "undefined local variable or method `current_user'" in the grid. Using Rails 4.2.4.

**The controller:**

class VwCurrentSectionStudentsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @params = params.fetch(:vw_current_section_students_grid, {})
    @params = @params.merge(current_user: current_user)
    Rails.logger.debug("params: " + @params.inspect)  
    @grid = VwCurrentSectionStudentsGrid.new(@params) do |scope| 
            scope.page(params[:page]) 
    end
  end
end 

**The grid:**

class VwCurrentSectionStudentsGrid

  include Datagrid
  attr_accessor :current_user  
  
  #
  # Scope
  #
  
  scope do
        VwCurrentSectionStudent.joins(:instructor).where('people.email = ?',current_user.email)
  end

Any help would be much appreciated.

**Comment by flexloop** [comment]
I am new to Ruby. I don't think I understand scope.

**Comment by bogdan** [comment]
See the second code snippet here:
https://github.com/bogdan/datagrid/wiki/Scope
