### ISSUE TITLE
Default Sort Order Overrides Sort Order of Parent Object's Field

### ISSUE THREAD

**Issue by PirunSeng** [bogdan/datagrid#188]
Hi,
Datagrid is awesome. My current Rails app is almost all about datagrid.

Currently, I've added some fields of parent object into its children datagrid table. The sort order of the parent's field is overridden by the default sort order of the original grid.

I have two models as the following.

```
Client belongs to User
User has many clients
```

My ClientGrid class:

```
scope do
     Client.includes(:user).order('clients.status, clients.first_name')
end

column(:user, header: 'User' , order: proc { |scope| scope.joins(:user).order('users.first_name') }) do |object|
     object.user.first_name
end
```

When the grid is first rendered, it sorts the data by client status then first name as default correctly. However, when I try sorting the user column, it doesn't work, but when I try removing the default sort order, the user column sort order works well as expected.

Are you getting my point?
Hope you can help.
Thanks,

**Comment by bogdan** [comment]
Your point is an ActiveRecord issue I tried to fix for ages:

```
Client.order(:status).order(:first_name) # => ORDER BY clients.status, clients.first_name
```

In other words AR never changes already defined order inside relation.

You need to change `order` to `reorder` to make it work: in this case order will be overwritten correctly.

**Comment by PirunSeng** [comment]
Thanks so much @bogdan for quick response and a very helpful answer one!
It works like a charm by changing `order` to `reorder` inside the column's `:order` as you guided.
I've never noticed this behavior of AR.
