### ISSUE TITLE
Unable To Order Associated Object's Column

### ISSUE THREAD

**Issue by PirunSeng** [bogdan/datagrid#189]
Hi again,
My previous solved issue is about sorting parent object's column.

And now, I'm facing another problem in which I want to sort to the table by a children object's column.
I have two model as the following:
`Client has many Cases`
`Case belongs to Client`

My ClientGrid class:
```
scope do
     Client.includes(:cases, :user).order('clients.status, clients.first_name')
end

```
```
column(:cases, order: 'cases.case_type' ) do |object|
    object.cases.last.case_type
end
```

I have also tried using proc with `order` and `reorder` as the following but no success.

```
column(:cases, order: proc { |scope| scope.includes(:cases).reorder('cases.case_type') } ) do |object|
     object.cases.last.case_type
end

```
When I click the sort order button in the cases column, the table rows get re-rendered again, but not with the order of the cases column. They are ordered by the default sort order which are client status and client first name.

**Comment by PirunSeng** [comment]
My fault, sorry.
I have many columns and most of them are related one to another. It leads me lost my way sometimes.
I've updated some data, and the problem has gone.
I may want to reopen later if I can detect the problems correctly.

**Comment by bogdan** [comment]
In case you want to use `order` by a column from a different table, you should use `joins` instead of `includes` because the last one serves a different reason and doesn't force a table to be joined on the SQL level.
