### ISSUE TITLE
Filtered Results Displayed On Web Are Less Than The Exactly Correct Results Exported

### ISSUE THREAD

**Issue by PirunSeng** [bogdan/datagrid#190]
Hello,
I've got different amount of matched results between web view and exported data.

ClientGrid:
```
scope do
     Client.all
end

```
```
filter(:any_assessments, :enum, select: %w(Yes No)) do |value|
     if value == 'Yes'
          ids = scope.joins(:assessments).pluck(:id).uniq
          scope.where(id: ids)
     else
          scope.without_assessments
     end
end
```

Client Model:
`scope :without_assessments,  -> { includes(:assessments).where(assessments: { client_id: nil }) }`

I have 150 clients. 100 clients have one assessment for each while other 50 clients do not.
Scenarios:

1. Filter by "No" any assessments, return correct 50 results.
2. Filter by "Yes" any assessments, return only 20 correct results on web while exported results are correctly 100.

I tried the code directly in rails console, the results are all correct.
Hope you get my point. Feel free to ask me for any other detail if you like.

Thanks,

**Comment by bogdan** [comment]
Can you show the code that does the CSV export?

**Comment by PirunSeng** [comment]
My controller action:
```
def index
     @client_grid = ClientGrid.new(params[:client_grid])
     respond_to do |f|
      f.html do
        @client_grid.scope { |scope| scope.paginate(page: params[:page], per_page: 20) }
      end
      f.csv do
        send_data @client_grid.to_csv, type: 'text/csv',
                                       disposition: 'inline',
                                       filename: "client_report.csv"
      end
    end
end
```
And the view (haml):
= link_to 'Export', current_url(format: 'csv')

**Comment by bogdan** [comment]
You apply pagination only to the web so web will only return first 20 (if 1st page). CSV will export all of them.

In your current structure if I would select some fields in form and than press "Export" I would not receive those fields as selected on backend because "Export" is not part of the form and doesn't cause form submission. 
This is not a style I recommend in demo. Maybe this is intended... but you should know what you are doing.

I am not sure what `current_url` does. Are you sure all parameters are passed correctly to the "Export" link? Use web inspector or rails log on request to verify.
Which method do you use in `form`? If it is post, than `current_url` would probably ignore the form.

**Comment by PirunSeng** [comment]
Sorry, I should have mentioned that there's no pagination is rendered, that's why I said it shows only the 20 correct results.

Sure, the "Export" doesn't cause the form submission.

I've compared the current parameters and the parameters passed to the "Export" link. They'are the same.
The form is "Get" method as default. I do not override the form method.

**Comment by bogdan** [comment]
Can you reproduce the issue in console? Ex:

``` ruby
g = ClientGrid.new(any_assesments: "Yes")
g.assets.size # => ?
g.assets.to_a.size # => ?
g.rows.size # => ?
CSV.parse(g.to_csv).size # => ?
```

**Comment by PirunSeng** [comment]
Sure, the results are:
```
g = ClientGrid.new(any_assessments: "Yes")
g.assets = 83
g.assets.to_a.size = 83
g.rows.size = 83
CSV.parse(g.to_csv).size = 84
```

**Comment by bogdan** [comment]
So they are the same. 84 = 83 + header.
Is 83 a correct number?

The problem is somewhere in your controller and view.

**Comment by PirunSeng** [comment]
Sure, 84 includes the header.
And 83 is the correct results.

When I try filter clients with "No" any assessments, the results are correct both in Web and Exported.

**Comment by PirunSeng** [comment]
Heh @bogdan !
I thing my problem is the sum of results does not work well with pagination. Or the pagination itself does not work properly.
I've discovered something debugging with pry.

My scenarios:
1. First page
```
g.assets.size = 20
g.assets.to_a.size = 20
g.rows.size = 20
```
2. Second page (Since there is no pagination links are rendered, I manually add `&page=2` to url params)
```
g.assets.size = 20
g.assets.to_a.size = 0
g.rows.size = 0

g.assets.to_a.class # => WillPaginate::Collection
g.assets.to_a # => []
```

It seems like from second page, no any results for pagination to render.

What do you think?

**Comment by bogdan** [comment]
What is the output for `g.assets.to_sql` on the second page?

**Comment by PirunSeng** [comment]
Here it is:
`"SELECT  \"clients\".* FROM \"clients\" WHERE \"clients\".\"id\" IN (46, 29, 30, 31, 32, 33, 34, 35, 36)  ORDER BY clients.status, clients.first_name LIMIT 20 OFFSET 20"`

**Comment by bogdan** [comment]
Is it correct? If yes, execute it in console and see the output.... I am sure it will be the same as `g.assets.to_a`.

**Comment by PirunSeng** [comment]
Yes, both queries of `g.assets.to_a` and `g.assets.to_sql` are the same.
How is it then?

**Comment by bogdan** [comment]
Did you execute `ActiveRecord::Base.connection.select_all(g.assets.to_sql)`?

**Comment by PirunSeng** [comment]
Sorry for late reply:

`SELECT "clients".* FROM "clients" WHERE "clients"."id" IN (4, 3, 25, 26, 27, 39, 33, 31, 34, 46, 40, 21, 5, 37, 32, 24, 38, 28, 30, 42, 29, 41, 36, 23, 44, 22, 45, 43, 35)`

**Comment by PirunSeng** [comment]
Hi @bogdan !
I'm bringing my solution in case you like to know.
I've changed:
`ids = scope.joins(:assessments).pluck(:id).uniq`
to
`ids = Client.joins(:assessments).pluck(:id).uniq`

The differences when I debug:
`scope.joins(:assessments).pluck(:id).uniq`

`SELECT DISTINCT "clients"."id" FROM "clients" INNER JOIN "assessments" ON "assessments"."client_id" = "clients"."id" LIMIT 20 OFFSET 0`

`Client.joins(:assessments).pluck(:id).uniq`

`SELECT DISTINCT "clients"."id" FROM "clients" INNER JOIN "assessments" ON "assessments"."client_id" = "clients"."id"`

I can understand that when I use scope to join with the assessments, the scope in controller gets applied, and yes, with the pagination scope (20).

I'm afraid my solution is out of DataGrid spec. If so, I would be appreciate for any refactoring. Otherwise, I will want to close this issue.
Thanks,
