### ISSUE TITLE
More operation for dynamic filter

### ISSUE THREAD

**Issue by Phanithism** [bogdan/datagrid#191]
Hi there,

I'm enjoy using your gem with a great filter functionality that have =, <= and => operations. I can see it need more operations. I'd suggest you to add more operations like !=, start_with and end_with to the gem. Looking forward to hearing from you. :)

**Comment by bogdan** [comment]
I don't like `!=` operation as I don't see the use of it. Can you show me a context where you would use that?

Also dynamic filter suppose to support custom operations defined by you. I think this is the direction we should go.

**Comment by Phanithism** [comment]
@bogdan There is quite an important case to use !=. eg: get all record except date != today or yesterday.

As I'm working on it, I hope to contribute more operations soon.

thanks

**Comment by Phanithism** [comment]
@bogdan I meant we could not filter except specific date like in the middle of the range.

Another eg: I have 10 students and I want to get all students for study tour except a student with name 'a'. that's also the case

I hope the 2nd example convince you well.

**Comment by bogdan** [comment]
@Phanithism not at all. Why would you need that? Is there anything special in this name? Or there is some special meaning in the name `a`, like `a` means "name unknown" where you've intended to use null instead?

**Comment by Phanithism** [comment]
you're little bit confusing with the 'a'.
'a' letter is an example of student name i meant.

**Comment by bogdan** [comment]
I am not... I have no idea why you would want to exclude the name `a` in the real world but include everything else. This use case is absolutelly irrelevant in real app. Make a real example instead.

**Comment by Uysim** [comment]
Some situation like student grade. Student grade can include A, B, C, D, E and F. If I want to get only pass student. So have to select all student who grad not equal to F. I think this is what @Phanithism wanting. But I think this can support why custom operations. Right @bogdan

**Comment by bogdan** [comment]
@Uysim yes, that sounds more real to me.

**Comment by bogdan** [comment]
This is now supported with the following syntax:

``` ruby
      filter(
        :condition, :dynamic, operations: ["=", "!=" ... ] # whatever you want to support as operations
      ) do |(field, operation, value), scope|
        if operation == "!="
          scope.where("#{field} != ?", value)
        else
          default_filter
        end
      end
```
