### ISSUE TITLE
Column Disappears when I add html: true

### ISSUE THREAD

**Issue by noahc** [bogdan/datagrid#193]
So, I have something that looks like this:

`column(:status) {"Yellow"}  `

But when I add `html: true` it disappears when I refresh the page.

`column(:status, html: true) {"Yellow"} `

Ultimately, what I want to do is display a button when the status is set to a certain value, so I think I need to have html: true to do that. Is that correct and why does it disappear when I add the html true to the column.

**Comment by bogdan** [comment]
Yes, it looks very weird. I think there is some special condition bug in datagrid or on your end. Can you show the full grid, controller and view code?

**Comment by noahc** [comment]
grid:

```ruby
class ProducerAuthorizationLogsGrid

  include Datagrid

  scope do
    ProducerAuthorizationLog
  end

  filter(:status, :string)

  column(:status, html: true) {"Yellow"}
  column(:bond_number)
  column(:created_at) {|model| model.created_at.in_time_zone('Central Time (US & Canada)').strftime("%m/%d/%Y %I:%M %p") }
  column(:error_message)
  column(:principal_state)
  column(:obligation_state)
  column(:licensed_state)
  column(:producer_id)
end
```

view:

```haml
%br
%br

.col-md-2
  = datagrid_form_for @grid, method: :get, url: producer_authorization_logs_path

.col-md-10
  = paginate(@grid.assets)

  %table.table
    %thead
      %tr
      - @grid.header.each do |column|
        %th
          = column
    %tbody
    - @grid.rows.each do |row|
      %tr
      - row.each do |item|
        %td= item

= paginate(@grid.assets)
```

Controller:

```ruby
class ProducerAuthorizationLogsController < ApplicationController

  def index
    @grid = ProducerAuthorizationLogsGrid.new(params[:producer_authorization_logs_grid]) do |scope|
      scope.page(params[:page])
    end
  end
  
end
```

Is this what you need?

**Comment by bogdan** [comment]
Your view is incorrect because `@grid.rows` returns only non-html columns.

Why you can't use the `datagrid_table` helper?

**Comment by noahc** [comment]
Yes, that will work. The reason I did it this way was to better integrate it with bootstrap, but I think I can just copy down the partials and manipulate them.

**Comment by bogdan** [comment]
I made some adaptations for `datagrid_rows` in master to allow something that you supposed to do.

Now the thing you want is achievable with:

``` haml
= datagrid_rows(@grid) do |row|
  %tr
    - row.each do |value|
       %td= value
```

You may try that from master

**Comment by noahc** [comment]
Ahh, thanks.

Does your change add a lot of complexity? For what I needed, I just ran the rake task to copy down the partials to edit them. I would have had to edit them eventually anyway.

**Comment by bogdan** [comment]
Not a lot, I consider that style a good idea anyway in case you want to do many custom layouts instead of shared partial

**Comment by noahc** [comment]
Yeah, that makes sense. Thanks for doing that. The helper works for us now, but I appreciate the flexibility. 

Thanks again.
