### ISSUE TITLE
Filter with different display value vs selection value

### ISSUE THREAD

**Issue by cmcguff** [bogdan/datagrid#194]
I have a filter that looks like this:

```
  filter(:status, :enum, 
    :select => ['Draft','New', 'Paid', 'Approved', 'Escalated', 'Withdrawn', 'Declined'],
    multiple: true
  )
```

as an example, I'd like the filter to apply based on "New" but display "Requested" in the view, is there any way to achieve this?

**Comment by bogdan** [comment]
Sure you may pass an Array like this:

``` ruby
select: [[value, key], [value, key]]
```

In this cases `value` will be used in UI and `key` in the grid object and query.

Other option would be:

``` ruby
filter(....) do |scope, value|
    scope.where(status: value == "Requested" ? "New" : value)
end
```
