### ISSUE TITLE
Rails 5 dependency compatability issues: MongoID

### ISSUE THREAD

**Issue by ktec** [bogdan/datagrid#198]
Trying to include the latest release (`~> 1.5.0`) in a Rails 5 application results in:

```
Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    datagrid (~> 1.5.0) was resolved to 1.5.0, which depends on
      mongoid (= 3.1.7) was resolved to 3.1.7, which depends on
        activemodel (~> 3.2)

    rails (>= 5.0.0) was resolved to 5.0.0, which depends on
      activemodel (= 5.0.0)

    rails (>= 5.0.0) was resolved to 5.0.0, which depends on
      activemodel (= 5.0.0)
```

After looking at the Gemfile I can see the `mongoid` dependency is only necessary when using `:mongo` group, however the gemspec forces it for all users. Is there any way around this?

**Comment by bogdan** [comment]
1.5.0 has a dependencies bug. I've released 1.5.1 to fix the issue: https://rubygems.org/gems/datagrid

Please use that version.
