### ISSUE TITLE
Display row number?

### ISSUE THREAD

**Issue by charzone95** [bogdan/datagrid#199]
Hi. Is there any method to display the row number in the first column? It's like a Serial Column.

**Comment by bogdan** [comment]
You may use the following snippet:

``` ruby
  column(:number) do |_, grid|
    grid.row_count
  end

  def row_count
    @row_count ||= assets.offset_value || 0
    @row_count += 1
  end
```

Maybe I should automate it somehow, but it is still in plans

**Comment by charzone95** [comment]
Thanks it works
