### ISSUE TITLE
Is there a possibility to sort a column locally, and not with SQL ?

### ISSUE THREAD

**Issue by kofronpi** [bogdan/datagrid#202]
Hello,
Thanks for the great work on datagrid!

I have an ordered scope with a 10-records limit:
`scope.where(thing_id: params[:thing_id]).order(global_score: :desc).limit(10)`

 When I try to sort the `global_score` column from lowest to highest, it re-renders the full datagrid with a SQL query and shows records which were not in the initial scope (order + limit) but are in the table ! 

I'd just like to sort the 10 initial records from the scope. 

Is that possible ?

**Comment by bogdan** [comment]
It depends on how the scope is built and when you want to apply the order.

The `order_by_value: true` column option can be the solution.
Other idea would be to move from ActiveRecord to Array completely and define the scope as Array. That would require to rewrite all filters for array too... If you can show full grid source code, that could help.

**Comment by kofronpi** [comment]
```

  class ThingsController < ApplicationController
    def index
      @grid = UserThingsGrid.new(params[:things_controller_user_things_grid]) do |scope|
        scope.where(container_id: params[:container_id])  \
          .order(global_score: :desc).limit(10)
      end
    end

    class UserThingsGrid
      include Datagrid

     # not really satisfying at the moment, to change
      def row_count
        @row_count ||= assets.offset_value || 0
        @row_count += 1
      end

      scope do
        Thing
      end

      column(:rank) do |_, grid|
        grid.row_count
      end
      column(:name)
      # the column I want to sort locally
      column(:duration)
      column(:global_score)
    end
  end
```

Thanks for your help !

**Comment by kofronpi** [comment]
@bogdan  It works, thanks ! I am closing this issue but I have another, related question : is there a way to keep pretty URLs when sorting ?

**Comment by bogdan** [comment]
You should do some powerful tricks for that. 

Run `rake datagrid:copy_partials` than modify `app/views/datagrid/_order_for.html.erb` to format an URL in the way you like. Ensure to add some controller code to process the pretty URL params and push them to grid.
