### ISSUE TITLE
attr_accessor cannot be used within filter block

### ISSUE THREAD

**Issue by PirunSeng** [bogdan/datagrid#207]
Hi there,
I've been implemented DataGrid within my project so far, and it's been cool.

Anyway, just now I want to use the attr_accessor within my filter block which returns scope with some chain of current_user for example, but got undefined method "current_user" error.
attr_access can be used as options of enum select, but not within the filter block as I mention above.

I'll write down some code later if this is not understood enough.

**Comment by bogdan** [comment]
Here is the way you can do it:

```
class Grid
  attr_accessor :current_user

  filter(:owned_by_me, :boolean) do |value, scope, grid|
    scope.owned_by(grid.current_user)
  end
end
```

**Comment by PirunSeng** [comment]
I'm afraid this does not work.

```
class ClientGrid
  attr_accessor :current_user

  filter(:gender, :enum, select: %w(Male Female)) do |value, scope, grid|
    value == 'Male' ? scope.male.where(user_id: current_user.id) : scope.female.where(user_id: current_user.id)
    # binding.pry
  end
end
```
```
class ClientsController < ApplicationController
  def index
    @client_grid = ClientGrid.new(params.fetch(:client_grid, {}).merge!(current_user: current_user))
    # binding.pry
  end
end
```

When I try `@client_grid.current_user` in my ClientsController, it returns my current user correctly. But when I try `grid.current_user` in my gender filter block of ClientGrid, it returns nil.

Another thing I wonder is that both `@client_grid` and `grid` objects do not have `current_user` attribute, but I can get the current user in my controller but not the grid class.
