### ISSUE TITLE
Filter by using sql query with if else condition

### ISSUE THREAD

**Issue by manikimpinge** [bogdan/datagrid#208]
I have a Target Model and want to fetch users from filters and sql query. How can I do that?

``` ruby
def action
  if params.has_key?("query")
		@targets = Target.find_by_sql(params[:query])	
	else
		@grid = TargetsGrid.new(params[:targets_grid]) do |scope|
      scope.page(params[:page])
    end
	end
end
```

So, if params has query then I want to run sql query, fetch targets and perform filters. If no query, then display all targets.

**Comment by manikimpinge** [comment]
I found method to overwrite scope

@grid.scope { Target.find_by_sql("select * from targets where id = 16") }

But It creates error:
ActionView::Template::Error (undefined method `preload' for #<Array:0x00000005d69700>):
    26: 	<%#= datagrid_form_for @grid, :method => :get, :url => people_path  %>
    27: 	<%= button_to "Check All", "#", class: "pull-right", id: "select_all_targets", style: "margin: 10px 0 10px 0" %>
    28: 	<%= form_tag "/add_target_list?t=f", id: "select_multi_target" do %>
    29: 		<%= paginate(@grid.assets) %>
    30: 		<%= datagrid_table @grid %>
    31: 		<%= paginate(@grid.assets) %>
    32: 	<%end%>

**Comment by bogdan** [comment]
The case is tough because of a way ActiveRecord works. When you do `find_by_sql` do you have any pagination? Are you sure you are fine without it?

I can propose the following:

``` ruby
target_ids = Target.find_by_sql("select * from targets where id = 16").map(&:id)
@grid.scope { Target.where(id: target_ids) }
```

**Comment by manikimpinge** [comment]
@grid = TargetsGrid.new(params[:targets_grid]) do |scope|
  	scope.page(params[:page])
end
if params.has_key?("query")				
    target_ids = Target.find_by_sql("select * from targets where id = 16").map(&:id)
	@grid.scope { Target.where(id: target_ids) }
end

Error:

ActionView::Template::Error (undefined method `total_pages' for #<Target::ActiveRecord_Relation:0x007f6ffd794a90>):

**Comment by bogdan** [comment]
``` ruby
@grid.scope { Target.where(id: target_ids).page(params[:page]) }
```

**Comment by bogdan** [comment]
Hope it helped. Reopen if any issues.
