### ISSUE TITLE
Text in filters after locale switch is not updated

### ISSUE THREAD

**Issue by Egrace** [bogdan/datagrid#209]
Hello. I have a pleasure to develop apps with your gem, but today I found an issue.
There is one similar issue that was already fixed: https://github.com/bogdan/datagrid/issues/169 (thank you for this).
When I switch locale, text in filters on page remains from old locale. Seems that strings just caching somewhere and ruby calls filter building code only once.
Code of filters looks like this:
```
  filter(:date, :enum, select: proc { |grid| grid.dates_select_options },
         include_blank: I18n.t('customer.reviews.filters.date.blank')) do |value|
    posted_in(value.to_i.months.ago.to_date..Date.today) if value.to_i.positive?
  end

  def dates_select_options
    {
      I18n.t('customer.reviews.filters.date.values.6_months') => 6,
      I18n.t('customer.reviews.filters.date.values.12_months') => 12,
      I18n.t('customer.reviews.filters.date.values.2_years') => 24
    }
  end
```
I think that it will be correct if text in filters will update after locale switching.

**Comment by bogdan** [comment]
I can not reproduce the issue with `select` option. Fixed the issue with `include_blank` that should accept proc now... please check the functionality by using the gem from master and tell me works fine for you, I'll make the release.

**Comment by Egrace** [comment]
Thank you, for ultrafast fix, now it works fine!
P.S.
With `select` was all ok :)

**Comment by bogdan** [comment]
Use 1.5.2.
