### ISSUE TITLE
Filter with modifier

### ISSUE THREAD

**Issue by akam-it** [bogdan/datagrid#211]
Hello,

Is it possible to filter with '=' or 'like'? It is like simple filter(not dinamic, because it add additional field) but with modifier select filed 

something like filter(:src, :string, :operations => ['=', '=~'], :header => "Source")

**Comment by bogdan** [comment]
I made a patch in master that just hides the input when you specify only one option in select of dynamic filter. So in your case it should work like this:


``` ruby
filter(:src, :dynamic, select: [:src], operations: %w(= =~), header: "Source")
```

Please use the gem from master branch.

I will make release in a few days.

**Comment by akam-it** [comment]
thats worked, thank you! may be better if operations input and input field will be at one line? (dynamic_filter css class)

**Comment by bogdan** [comment]
It should be already set if you are using the default datagrid CSS or you should style it yourself if not.
