### ISSUE TITLE
AND OR conditions

### ISSUE THREAD

**Issue by akam-it** [bogdan/datagrid#212]
Is it possible to combining the AND and OR conditions?

for example I want to get records with date today AND firstname "A" OR lastname "A"

I searched issues but find nothing

**Comment by bogdan** [comment]
How do you imagine the UI for that?

**Comment by akam-it** [comment]
May be it will be two additional radiobutton "AND(default)" and "OR"
and set :andonly (for example) in filter(:calldate, :datetime, :andonly ,range: true, default: proc {[1.day.ago, Time.now]})

**Comment by bogdan** [comment]
That looks terrible for both - end user and developer.

I would recommend you the following:

``` ruby
filter(:calldate, :datetime, range: true, default: ...)
filter(:name, :string) do |value|
  where("first_name = ? OR last_name = ?", value, value)
end
```

It hardly depends on which functionality you want to be available for the end user.
What I learned from years of making grids: users never want OR. If you need OR between filters, you do something wrong.

**Comment by akam-it** [comment]
There is call history table. In one scenario I want to find inbound OR outbound calls to/from number 100 only today. In the second scenario I want to find only inbound calls to 100 AND from 101.

There is no other way to do it without OR :(

**Comment by bogdan** [comment]
Here is the way:

``` ruby
filter(:inbound_number, :integer, dummy: true)
filter(:outbound_number, :integer, dummy: true)
filter(:conjuction, :enum, select: %w(AND OR), inlude_blank: false, default: 'AND') do |conjuction, scope, grid|
    scope.where("outbound_number = ? #{conjuction} inbound_number = ?", grid.inbound_number, grid.outbound_number)
  end
```

**Comment by akam-it** [comment]
Thank you for your try, but not working
1. dummy filter can't be dynamic filter? (with operations: %w(= =~))
2. If fields are empty that sql generate - AND (outbound_number = NULL AND inbound_number = NULL)

**Comment by bogdan** [comment]
1. Yes, they can. 
2. Sorry I didn't handle nil cases.

I also want to note that things you are trying to do are really advanced, therefore there will be no 3 lines of code solution.

But here it is:

``` ruby
filter(:inbound_number, :dynamic,
  include_blank: false, operation: %w(= =~), select: [:inbound_number], dummy: true)

filter(:outbound_number, :dynamic, 
  include_blank: false, operation: %w(= =~), select: [:outbound_number], dummy: true)

OPS_SQL_MAP = {"=" => "=", "=~" => "like"}
filter(
  :conjuction, :enum, select: %w(AND OR), include_blank: false, default: 'AND'
) do |conjuction, scope, grid|
  conditions = [grid.inbound_number , grid.outbound_number].select(&:last)
  query = conditions.map  do |attribute, operation, value|
   value = "%#{value}%" if operation == "=~"
    " #{attribute} #{OPS_SQL_MAP[operation]} #{value}"
  end.join(conjuction)
  scope.where(query)
end
```

**Comment by akam-it** [comment]
Thank you for help!
