### ISSUE TITLE
self to params

### ISSUE THREAD

**Issue by akam-it** [bogdan/datagrid#213]
Hello, is scenario like this is possible?

```
column(:src, mandatory: true, description: :src) do
  Person.callerid(src)
end

<tr>
  <% grid.html_columns(*options[:columns]).each do |column| %>
    <td class="<%= datagrid_column_classes(grid, column) %>"
        <% if column.options[:description] %>
            title="<%= column.options[:description] %>"
        <% end %>>
    <%= datagrid_value(grid, column, asset) %></td>
  <% end %>
</tr>

**Comment by bogdan** [comment]
Everything is possible.

It largely depends on what do you expect to happen.
Can you explain what you are trying to do?

**Comment by akam-it** [comment]
I just want to display in table via title another model field.
In provided example I want to display in row of table modified model value(Person.callerid(src)) and in title raw value(src).
Or display via title another field of model.

**Comment by bogdan** [comment]
I would do it like this:

``` ruby
column(:src, mandatory: true, description: :src) do |model|
  format(Person.callerid(model.src)) do |value|
    content_tag(:div, value, title: model.src, style: "...")
  end
end
```

You may need to add some styles to your `div` to make it fill the whole table cell and be indistinguishable from `<td>` in the UI.

In case you still want to assign `title` into `<td>` for some reason, here is how you can support `:description` attribute:

``` erb
<tr>
  <% grid.html_columns(*options[:columns]).each do |column| %>
    <td class="<%= datagrid_column_classes(grid, column) %>"
        <% if column.options[:description] %>
            title="<%= model.send(column.options[:description]) %>"
        <% end %>>
    <%= datagrid_value(grid, column, asset) %></td>
  <% end %>
</tr>
```
