### ISSUE TITLE
Support for decimal filter

### ISSUE THREAD

**Issue by haydencarlson** [bogdan/datagrid#214]
I'm using mariaDB and want to filter my amount which is scale 8 and cannot because there is no filter type.
Float does not work.

**Comment by bogdan** [comment]
Can you explain in more details why float doesn't work?

**Comment by haydencarlson** [comment]
Whenever I try to filter by decimal it returns undefined for the whole table.

**Comment by bogdan** [comment]
> filter by decimal

Please provide a code sample. Better without controller just with console.

> it returns

What is "it"?

> undefined

What is undefined? Is it a JS constant? Did you mean `nil`?

> for the whole table

How is it possible to return undefined for something? Do you mean empty table?
