### ISSUE TITLE
Report display format 

### ISSUE THREAD

**Issue by kirantpatil** [bogdan/datagrid#217]
Hi,

I would like to display the report as shown in below screenshot.

I have taken example from the link http://datagrid.herokuapp.com/documents?page=6

```
Date           2011-12-01        2011-12-02         2011-12-03
Rating         2                   3                4
Author         xxx                yyy               zzz
Title          book1              book2             book3
```

How to achieve it ?

![screenshot from 2017-04-21 16 31 56](https://cloud.githubusercontent.com/assets/1178055/25274983/94cdf560-26b0-11e7-9687-5f1f6aa8402f.png)

Thanks.

**Comment by bogdan** [comment]
You can achieve that with CSS: http://jsfiddle.net/XKnKL/3/

**Comment by kirantpatil** [comment]
Great. Thank you Sir.

**Comment by smitakiran25** [comment]
I added this css in my code row is not displaying correctly.
I already updated the code in the 
https://github.com/smitakiran25/school_app 
the table displaying like this 
![screenshot from 2017-05-31 19-50-49](https://cloud.githubusercontent.com/assets/11611902/26636574/da5ed1b8-463a-11e7-9915-d3e5daa5ff51.png)


please tell me how to display table correctly
