### ISSUE TITLE
uninitialized constant StudentListsController::StudentListsGrid

### ISSUE THREAD

**Issue by smitakiran25** [bogdan/datagrid#218]
i wanted to list the students depending on there dob i created students database and for reports created student list grid 
i generated the student_list grid, after generating the student_list_grid i am getting that error 

**student_lists_controller** 

``` ruby
class StudentListsController < ApplicationController

  def index
    @student_lists_grid = StudentListsGrid.new(params[:student_lists_grid]) do |scope|
      scope.page(params[:page])
    end
  end
end


**student_lists_grid.rb**

class StudentListsGrid

  include Datagrid

  scope do
    StudentList
  end

  filter(:year, :enum,
     :select => lambda { TimeEntry.all.any? ? (TimeEntry.minimum(:date).year..TimeEntry.maximum(:date).year) : []},
    :include_blank => false,
    :default => lambda {Date.today.year}
  ) do |value|
    self.where(["extract(year from time_entries.date) = ?", value.to_i])
  end

  column(:name, :header => "Student Name", :order => "students.name")
  column(:dob, :header => "DOB", :order=> "students.dob") do |model|
    model.students.date
  end
    column(:section, :header => "Student section", :order => "students.section")
end

**model/student.rb**

class Student < ApplicationRecord
  has_many :student_list
end

**app/views/student_lists/index.html.erb**

<%= datagrid_form_for @student_lists_grid, :method => :get, :url => student_lists_path %>

<%= datagrid_table (@student_lists_grid) %>
<%= paginate @student_lists_grid.assets  %>
```

please tell me is am I working in correct way

**Comment by smitakiran25** [comment]
student_list is located in app/grids/student_lists_grid.rb

**Comment by bogdan** [comment]
Can you try to move `student_lists_grid.rb` to `app/models` and tell me if it is working?

**Comment by smitakiran25** [comment]
I restarted the server and but its not working 
i moved student_lists_grid.rb to app/models that als not working the same error is coming 

![screenshot from 2017-04-25 18-22-41](https://cloud.githubusercontent.com/assets/11611902/25386279/75554814-29e4-11e7-9891-da8e6dcefaf3.png)

**Comment by bogdan** [comment]
It is not the same..... It is different.

Do you have the `app/models/student_list.rb` file? What is inside?

**Comment by smitakiran25** [comment]
there is no file called student_list.rb file in model, when i generated the student_list grid scaffold default its created 
app/views/student_list.html.erb
app/grid/student_lists_grid.rb
app/controller/student_lists_controller.

i have created one student scaffold and one more grid scaffold student_list

**Comment by bogdan** [comment]
You need to make models too... they are not part of datagrid scaffold.

**Comment by smitakiran25** [comment]
Thank you  sir i have created model and that error fixed.
