### ISSUE TITLE
uninitialized constant StudentListsGrid::StudentLists

### ISSUE THREAD

**Issue by smitakiran25** [bogdan/datagrid#219]
i have two scaffold one is student and anohter one is student _list grid scaffold 

student  db contains all the student details, i want to display a students whose dob is same as selected year so I generated the grid scaffold called student_list 
 code is 

**app/views/students/_form.html.erb**

 <%= form_for(@student) do |f| %>

      <div class="field">
         <%= f.label :name %>
         <%= f.text_field :name %>
      </div>

      <div class="field">
        <%= f.label :section %>
        <%= f.text_field :section %>
      </div>

     <div class="field">
         <%= f.label :dob %>
         <%= f.date_select :dob %>
     </div>

     <div class="field">
       <%= f.label :standard %>
       <%= f.text_field :standard %>
     </div>

     <div class="actions">
         <%= f.submit %>
     </div>
     <% end %>

**app/views/student_lists/index.html.erb**

     <%= datagrid_form_for @student_lists_grid, :method => :get, :url => student_lists_path %>

     <%= datagrid_table (@student_lists_grid) %>
     <%= paginate @student_lists_grid.assets  %>

**app/controller/student_lists_controller.rb**

      class StudentListsController < ApplicationController

      def index
      @student_lists_grid = StudentListsGrid.new(params[:student_lists_grid]) do |scope|
        scope.page(params[:page])
      end
      end
       end

**app/grid/student_lists_grid.rb**

        class StudentListsGrid
 
          include Datagrid
               scope do
             StudentLists.select(
              "student_list.id, students.name, students.dob,students.section,student.year_of_joined"
              ).joins(:student_lists => :student ).group("student.name", "students.dob", 
             "students.section","student.year_of_joined").order("students.name")
                end

             filter(:dob, :enum,
                 :select => lambda { Student.all.any? ? 
                     (Student.minimum(:date).year..Student.maximum(:date).year) : []},
                         :include_blank => false,
                          :default => lambda {Date.today.year}
                             ) do |value|
                       self.where(["extract(year from students.dob) = ?", value.to_i])
                    end

                     filter(:year, :enum,
                          :select => lambda { Dob.all.any? ? 
                         (Dob.minimum(:date).year..Dob.maximum(:date).year) : []},
                        :include_blank => false,
                        :default => lambda {Date.today.year}
                            ) do |value|
                            self.where(["extract(year from students.dob) = ?", value.to_i])
                           end

               column(:name, :header => "Student Name", :order => "students.name")
               column(:dob, :header => "DOB", :order=> "students.dob") do |model|
                 model.students.date
               end
              column(:section, :header => "Student section", :order => 
               "students.section")
                 end

            **app/models/student.rb**

            class Student < ApplicationRecord
               has_many :student_list
               end
 
**app/models/student_list.rb**

      class StudentList < ApplicationRecord
         belongs_to :student
          end
i want to display year drop down list and report of student list i am getting the following error
![screenshot from 2017-04-26 16-23-05](https://cloud.githubusercontent.com/assets/11611902/25431072/ae1665a8-2a9c-11e7-922a-9487a3180e90.png)

**Comment by bogdan** [comment]
`StudentLists` => `StudentList`. 

You are asking too newbee questions.... Please be more attentive.
