### ISSUE TITLE
Elasticsearch integration

### ISSUE THREAD

**Issue by khusnetdinov** [bogdan/datagrid#220]
At my project i faced with problem to do request to DB and ElasticSearch with params that I receive from grid. So I need to use default scope and scope that depends on ES query and fetched from DB. And I see that for this i need 2 scopes defined in GridClass. I try to reload scope after initialization but for my it's not good solution. I need get all records before I send them to GridClass.

What you you think about additional scope for ES purpose?

**Comment by bogdan** [comment]
Your task very unclear to me.... You didn't give me any specifics nighter on your requirement nor code samples.... 

I'll try to guess what you meant anyway....
The only thought I have from here is use 2 grids and reuse code between them with module:

``` ruby
class ElasticSearchGrid
  scope {...}
  include SharedCode
end

class DbGrid
  scope {...}
  include SharedCode
end

def <controller action>
  @db = DbGrid.new(params[:grid])
  @elastic = ElasticGrid.new(params[:grid])
end
```

**Comment by khusnetdinov** [comment]
@bogdan Thanks, solution was found.
