### ISSUE TITLE
Filter is not working 

### ISSUE THREAD

**Issue by smitakiran25** [bogdan/datagrid#221]
When i select the year of dob filtered data is not displaying please tell me what mistake i am doing hear 
I have added my code in https://github.com/smitakiran25/school_app

**Comment by bogdan** [comment]
On this line:

https://github.com/smitakiran25/school_app/blob/master/app/controllers/student_lists_controller.rb#L4

Change `:student_lists` to `:student_lists_grid`.

**Comment by smitakiran25** [comment]
after changing :student_lists to :student_lists_grid. syntax error is coming 
![screenshot from 2017-05-03 15-27-06](https://cloud.githubusercontent.com/assets/11611902/25656157/509aa5aa-3015-11e7-997c-663805dddf3e.png)

**Comment by bogdan** [comment]
The code in your filter is written for PostgreSQL not for SQLite.... I am not an SQLite expert and can't advice anything as it is far beyond the datagrid. You may ask on http://stackoverflow.com how to rewrite the code for SQLite.

**Comment by kirantpatil** [comment]
@bogdan, thanks for the suggestion. We were not aware that the code is specific to Postgresql.

**Comment by smitakiran25** [comment]
Thank  you sir its working fine in Postgresql
