### ISSUE TITLE
Two grids on same page different tabs

### ISSUE THREAD

**Issue by haydencarlson** [bogdan/datagrid#223]
So i'm having an issue where I have two grids on a page both the exact same just slightly different scope and only one of the grids pagination works. If i comment one out the other works and vise versa.

`			<div id="ttab1_nobg" class="tab-pane active">
                    <%= datagrid_form_for @grid, url: transactions_path %>
                    <%= datagrid_table @grid %>
									</div>
									<div id="ttab2_nobg" class="tab-pane">
                    <%= datagrid_form_for @sandbox_grid, url: transactions_path %>
                    <%= datagrid_table @sandbox_grid %>
								  </div>`

That's what my html file looks likes.

Any help appreciated

**Comment by bogdan** [comment]
I don't see the pagination display code here. Also you have a separated `<form>` for each grid. It will cause parameters only from one form  to be submitted at a time.... so when you filter first grid, second one parameters are reset. This is probably not the thing you want.
You need to combine them into one html form like this:

``` haml
= form_tag transactions_path do
  = fields_for :grid, @grid do |f|
    - @grid.filters.each do |filter|
      = f.datagrid_label filter
      = f.datagrid_filter filter
  -# same for @sandbox_grid :sandbox_grid
  = submit_tag
```

You need to use a different pagination parameter for each grid in your controller. Something like:

``` ruby
@grid = Grid.new(params[:grid]) {|s| s.page(param[:page]) }
@sandbox_grid = Grid.new(params[:sandbox_grid]) { |s| s.page(params[:sandbox_page]) }
```
