### ISSUE TITLE
ORM Driver not found for scope: :row_class.

### ISSUE THREAD

**Issue by smitakiran25** [bogdan/datagrid#224]
I am trying to add color depends on sections in  the data grid i already updated the code in the https://github.com/smitakiran25/school_app  i am referring the code in the https://github.com/bogdan/datagrid/wiki/Frontend  in Highlight rows 
Highlight rows

If you would like to attach a different html class to each row making it stylable with CSS, you add it this configuration option by modifying built-in partial _row.html.erb:

```
-<tr>
+<tr class="<%= grid.respond_to?(:row_class) ? grid.row_class(asset) : "" %>">
   <% grid.html_columns(*options[:columns]).each do |column| %>
     <td class="<%= datagrid_column_classes(grid, column) %>"><%= datagrid_value(grid, column, asset) %></td>
   <% end %>
```

It will make it possible to define column HTML class in each grid like this:

```
class IssuesGrid
  include Datagrid
  scope { Issue }

  def row_class(issue)
    case issue.status
    when "fixed" then "green"
    when "rejected" then "red"
    else "blue"
    end
  end
end
```

I am getting this error 
![screenshot from 2017-05-09 11-14-20](https://cloud.githubusercontent.com/assets/11611902/25837012/d325587a-34a8-11e7-938a-a253e8642e20.png)

please tell me how to resolve this issue

**Comment by bogdan** [comment]
Show me the full trace of the exception.

**Comment by smitakiran25** [comment]
Thank You sir, 
I changed the code but row color is not coming 
i updated the code in git hub https://github.com/smitakiran25/school_app
![screenshot from 2017-05-09 17-45-55](https://cloud.githubusercontent.com/assets/11611902/25850388/b6e2c67a-34df-11e7-909f-41d37e4f3bf5.png)

i am not getting any changes please tel me where i am doing mistake

**Comment by bogdan** [comment]
You should start understanding what you are doing. Please start from here: https://www.google.com.ua/search?q=what+is+CSS&oq=what+is+CSS&aqs=chrome..69i57j0l5.3223j0j7&sourceid=chrome&ie=UTF-8#q=how+to+use+css+classes


Also there is http://stackoverflow.com/ for questions like that.

**Comment by smitakiran25** [comment]
Thank You Sir Its Working.

**Comment by kirantpatil** [comment]
@smitakiran25, please mention the steps you have taken to resolve this issue. It will benefit others as well.
