### ISSUE TITLE
Column is shown in html, even when i specify html: false

### ISSUE THREAD

**Issue by landacorp** [bogdan/datagrid#228]
I want to make the same column to be shown differently, when it's "csv" and "html"

Example:

``` ruby
  column(:var, html: false)
  column(:var, html: true) do |v|
    content_tag :span do
      "<b>#{v}</b>"
    end
  end
```

But what happens - is:

In csv page: only the first one, which is right :)
In html page: i get both columns together   <- the problem

I use 1.5.4 version with Rails 5.1.1 , Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
Ubuntu

Thanks in advance

**Comment by bogdan** [comment]
Here is how to do that:

``` ruby
column(:var) do |v|
  format(v.var) do |value|
      content_tag :span do
        "<b>#{v}</b>"
      end
    end
end
