### ISSUE TITLE
[FAQ] How it is different from wice_grid ?

### ISSUE THREAD

**Issue by kirantpatil** [bogdan/datagrid#232]
Hi,

I came across [wice_grid](https://github.com/leikind/wice_grid) project, which looks same as that of datagrid.

Please let us know pro's and con's of both of them.

Thanks,
Kiran.

**Comment by bogdan** [comment]
@kirantpatil I never tried wice_grid so I will not be an expert and my opinion would not be arbitrary as I will argue for datagrid anyway.

**Comment by kirantpatil** [comment]
@bogdan, thanks for your opinion. I am awaiting community members reply.

**Comment by kirantpatil** [comment]
I am closing right now. Please feel free to provide your comments.

**Comment by benphelps** [comment]
`datagrid` focuses on keeping the majority of code outside of your views and `wice_grid` does the opposite, most of the code is kept in your views.  I feel like datagrid does a better job separating the grid logic and rendering logic, making for cleaner views (always a good thing).
