### ISSUE TITLE
Preserve Current URL Params on Sort or Filter

### ISSUE THREAD

**Issue by mshahidkhan** [bogdan/datagrid#234]
Hi,
First, I must say, this is a really nice datagrid implementation and very active responses on the issues raised.
I am not sure if this issue is already addressed. ( I already checked but could not find.)

Issue I am facing - when I sort a column, I lose existing URL Params.
**for example** - _localhost/expenses?param1=one&param2=two_  
when I sort grid, it changes to
__localhost/expenses?expenses_grid%5Bdescending%5D=false&expenses_grid%5Border%5D=expense_title_

Is there a way to preserve (or append) existing URL params?

Thanks!

**Comment by joemsak** [comment]
Came here to search for this issue :)

**Comment by bogdan** [comment]
@joemsak @mshahidkhan fixed an issue in master. Please check if the fix works for you and I'll make a release

**Comment by mshahidkhan** [comment]
Thanks @bogdan 
I am getting an error on 'request' used in renderer.rb
`undefined local variable or method 'request' for #<Datagrid::Renderer:0x6ccdb701>`

Am I missing anything here ?

**Comment by bogdan** [comment]
One more attempt to fix. Try current master.

**Comment by mshahidkhan** [comment]
Bingo! The fix works. Thanks a lot. 👍 
Could you please make an official release.
