### ISSUE TITLE
Columns: Issue when using `decorate do` and `html: true`

### ISSUE THREAD

**Issue by beNjiox** [bogdan/datagrid#243]
When using `html: true` in `columns()` and using `decorate do` things don't get decorated.
By browsing the code it seems that the moment you branch to handle `html: true` rendering you do not replicate the logic to take of the presenter.

Step to replicate:

- Create a datagrid with a `decorate do { }` block
- Have one column with `html: true` option passed
- Observe that `model` within the column block is not decorated

Let me know if you would like me to make a repository highlighting the bug.

Thanks!

**Comment by bogdan** [comment]
Fixed in 1.5.8
