### ISSUE TITLE
HTML options to filters

### ISSUE THREAD

**Issue by andresulivam** [bogdan/datagrid#246]
Hi! How to add html options to filters?
I tried a some tags like:
html_options: {}
html_attributes: {}
html: {}
Can I do this?

**Comment by bogdan** [comment]
Yes, you need to modify the built-in partials for that `rake datagrid:copy_partials`. Then modify `_form.html.erb` partial and access options with `filter.options[:html_options]`. In this way you can add any custom options to filter.

**Comment by ericksm3** [comment]
Hello, bogdan! 
Is there a way to add html attributes on the datagrid generated inputs? Like the  "placeholder" for example.

**Comment by bogdan** [comment]
Run `rake datagrid:copy_partials`. Change `_form.html.erb`:

``` diff
-      <%= f.datagrid_filter filter %>
+      <%= f.datagrid_filter filter, placeholder: filter.options[:placeholder] %>
```

Now you can use `:placeholder` option in filter definition:

``` ruby
filter(:value, :string, placeholder: "Specify Value")
```

**Comment by ericksm3** [comment]
Thank you so much! It worked :)

**Comment by andresulivam** [comment]
Thank you, Bogdan!
