### ISSUE TITLE
NoMethodError - Undefined "path_for" datagrid_order_path

### ISSUE THREAD

**Issue by cpeixejr** [bogdan/datagrid#247]
I've a RoR project and I'm trying to use Datagrid.
But when I access the index page the following error is shown:

NoMethodError in Reports#index

undefined method `path_for' for ActionDispatch::Http::URL:Module

![datagrid error](https://user-images.githubusercontent.com/38816922/39399496-0d0b6bd4-4af5-11e8-8d52-38759232a0a4.PNG)

Controller:

![controller](https://user-images.githubusercontent.com/38816922/39399519-6d801a46-4af5-11e8-8489-5e7ba430e402.PNG)

ReportsGrid:

![image](https://user-images.githubusercontent.com/38816922/39399529-a010a66a-4af5-11e8-9132-096faeb26e61.png)

 Any idea?

**Comment by cpeixejr** [comment]
View:

![image](https://user-images.githubusercontent.com/38816922/39399602-25c07208-4af7-11e8-90ca-e4bca0d6960f.png)

**Comment by bogdan** [comment]
Please, tell me which version of rails do you use?

**Comment by bogdan** [comment]
Unable to reproduce. If still an issue, please follow up.
