### ISSUE TITLE
How to get key from current filter?

### ISSUE THREAD

**Issue by PirunSeng** [bogdan/datagrid#249]
Hi There, thanks for a very cool gem.

I'm having this sample filter:

```
  filter(:name, :string) { |value, scope, grid|} do
    ...
  end
```

How can we get key from this filter which is either :name or "name" in this case? I want to use that key to do something inside that block. I had also posted the same question in stackoverflow [here](https://stackoverflow.com/questions/50737123/how-to-get-key-from-current-filter-of-datagrid-gem). On the other hand, I wonder if somebody could create `datagrid-gem` tag to stackoverflow.

**Comment by PirunSeng** [comment]
@bogdan thanks! Of course, I've done that. I just wonder if there is a more dynamically or better way to get the key. My scenario is to prevent a case that the developer might change the key of the filter, but they forget to also change the argument of that key. Eg:

```
filter(:name_changed, ...) do |value, scope, grid|
  grid.shared_filter_code(:name, value, scope, grid)
end
```

**Comment by bogdan** [comment]
``` ruby
alias_method :name=, :name_changed=
alias_method :name, :name_changed
```

Enjoy!
You may not need the second method aliasing only the writer. It depends on your use case.
