### ISSUE TITLE
URLs with Anchors and Search reset button

### ISSUE THREAD

**Issue by fabriciofreitag** [bogdan/datagrid#252]
If an URL with an anchor (i.e: "/books/1#readers") is passed to `datagrid_form_for`

The ancor is disregarded by the reset button:
`<a class="datagrid-reset button" href='/books/1'>Reset</a>`

Expected:
`<a class="datagrid-reset button" href='/books/1#readers'>Reset</a>`

**Comment by bogdan** [comment]
`anchor` is not passed to backend by the HTTP standard. So the link that retain anchor can not be generated because backend doesn't know about it.
You can simulate the behavior only using JavaScript.
Try something like this:

``` js
jQuery(function() {
  jQuery('.datagrid-reset').each(function(i, element) {
    jQuery(element).attr('href', jQuery(element).attr('href') + window.location.hash);
  });
});
```

**Comment by fabriciofreitag** [comment]
@bogdan thanks for the quick reply.
but then why the filtering (search button) works as expected when there's an anchor(keeping the selected tab) while reset sends me to the previous page?

**Comment by bogdan** [comment]
I can not confirm that. On my end, anchor vanishes for both Reset and Search buttons.
