### ISSUE TITLE
Feature - Datagrid with ActiveResource?

### ISSUE THREAD

**Issue by jonmchan** [bogdan/datagrid#263]
Datagrid supports activerecord - how difficult would it to be to use datagrid with active resource? Has anyone had any experience with this?

https://github.com/rails/activeresource

**Comment by bogdan** [comment]
It will be hard because activeresource doesn't support any kind of chained finding methods like `where(..).where(...).where(...)`. Datagrid expects this as a core feature to anything it can support.

However there is a hacky way to support activeresource with a constructions like this:

```
class MyGrid
  scope { [] }
  dynamic do
    scope do
       ActiveResourceModel.find(:all, params: attributes.slice(:one, :two))
    end
  end

  filter(:one, dummy: true)
  filter(:two, dummy: true)
end
