### ISSUE TITLE
datagrid字段过多导致拥挤

### ISSUE THREAD

**Issue by selfconfidence** [bogdan/datagrid#265]
datagrid字段过多导致拥挤, 无法显示完整,有没有什么办法能够在下面加一个移动行,随着鼠标移动去查看字段列表数据.

**Comment by bogdan** [comment]
Good morning,

I can't read Chinese well. Please use google translate or a friend to write your issue in english.

**Comment by selfconfidence** [comment]
That's settled. Thank you.
