### ISSUE TITLE
Little style issue

### ISSUE THREAD

**Issue by dux** [bogdan/datagrid#266]
this works as expected

```
      column :created_at do |model|
        model[:created_at].strftime('%d.%m.%y. %H:%M')
      end
```

but this fails with ArgumentError, and I think it should not. why do we need to provide col name if value is calculated?

```
      column do |model|
        model[:created_at].strftime('%d.%m.%y. %H:%M')
      end
```

**Comment by bogdan** [comment]
That is required if you work with columns in an advanced way and reference columns directly. However you are right that it is not required for simple use cases. I need to think about that.

**Comment by bogdan** [comment]
I think it doesn't worth to support unnamed columns because you would need a `header` anyway and there is so high probability you would need a name for a column for direct reference down the road.

**Comment by dux** [comment]
if no header provided then no header name. if no col name then no sorting options.

I generate click buttons directly on the grid, last col on the left, and do not want to have a header and sorting options. is that possible?

**Comment by bogdan** [comment]
You can do

``` ruby
class Grid
  self.default_column_options = {order: false, header: ""}
end
```

Hiding header in the UI requires to change built-in partials https://github.com/bogdan/datagrid/wiki/Frontend#modifying-built-in-partials
