### ISSUE TITLE
SQL Injection in Filter example

### ISSUE THREAD

**Issue by evan-duncan** [bogdan/datagrid#267]
The wiki page for filters [includes examples](https://github.com/bogdan/datagrid/wiki/Filters#filter-block) that will open up users to SQL injection.

```ruby
# easy use case:
filter(:name, :string) { |value| where("name ilike '%#{value}%'") }
```

You should update all example queries that are not properly sanitizing inputs so users less familiar with active record won't do bad things.

```ruby
# easy use case:
filter(:name, :string) { |value| where("name ilike ?", "%#{value}%") }
```

**Comment by bogdan** [comment]
Good suggestion, btw, you can update that too.
