### ISSUE TITLE
Pagy for pagination

### ISSUE THREAD

**Issue by joshmn** [bogdan/datagrid#269]
Anyone have any tips on getting Pagy plugged in for pagination? We have an above-average size of records and Kaminari and will_paginate just aren't cutting it as far as performance goes.

**Comment by bogdan** [comment]
You would need something like this in your controller:

``` ruby
@grid = MyGrid.new(params[:my_grid])
@pagy, @records = pagy(@grid.assets)
```

and your view:

``` haml
= datagrid_table(@grid, @records)
= pagy_nav(@pagy)
```

**Comment by saiqulhaq** [comment]
oh god, after 1 hour trying to integrate action policy, pagy with datagrid
finally I found this so easy
thanks
