### ISSUE TITLE
uninitialized constant Datagrid::Filters (NameError)

### ISSUE THREAD

**Issue by saydulk** [bogdan/datagrid#270]
I have a Rails app. when i run $ rails server it shows  uninitialized constant Datagrid::Filters (NameError)
![Screenshot from 2019-10-01 00-21-35](https://user-images.githubusercontent.com/1058663/65904997-80d37800-e3e1-11e9-8357-79d1eebe5d97.png)

**Comment by bogdan** [comment]
What is inside the `date_time_filter.rb` file?
Try to add `require 'datagrid'` on top of it.
Which version of rails do you use?
How do you plug `datagrid` to your `Gemfile` ?

**Comment by bogdan** [comment]
No followup, closing.
