### ISSUE TITLE
batch_size default

### ISSUE THREAD

**Issue by dgodd** [bogdan/datagrid#276]
In generating a CSV file which is foolishly large using datagrid, I discovered the `batch_size` class accessor. It appears to me that the docs specify that it has a default of `1000` (https://github.com/bogdan/datagrid/blob/master/lib/datagrid/columns.rb#L36) but that in reality the default is nil.

Assuming I am correct, I'm happy to submit a PR to either the docs or to set the default to be `1000`.

**Comment by bogdan** [comment]
Yes, lets fix that and add a test.
