### ISSUE TITLE
Chinese char are not shown in table

### ISSUE THREAD

**Issue by trselva** [bogdan/datagrid#279]
There is a Chinese string/char in the database. But when I show that in front end table using datagrid. It is not exactly showing as the Chinese string/char as shown in back-end DB, Instead it shows some non-readable things (i.e ?????????). How to display the Chinese letter in datagrid table for users as it is in Database.

**Comment by trselva** [comment]
Chinese/Japanese char is not displaying correctly with datagrid. is Datagrid converting it in UTF-8 ? 
there are certain columns have Chinese/Japanese names , those names should be displayed in the same format... pls let us know how to do this with datagrid.

**Comment by bogdan** [comment]
Datagrid should not do anything related to characters encoding. Are they displayed correctly without Datagrid? It looks like a general encoding problem that most likely needs to be solved at the frontend.
