### ISSUE TITLE
Link to grid with specific filter enabled

### ISSUE THREAD

**Issue by Ellerden** [bogdan/datagrid#290]
Hi! I have a Candidates grid with several filters (one is "Followed" - indicating that User is subscribed to the candidate). On another, Notifications page, I need to have a link to CandidatesGrid with 'Followed' filter enabled. Any suggestions on how to do that? Didn't see how to refer to the specific filter in docs. Thanks in advance.

**Comment by bogdan** [comment]
Hey,

You can do it like this:

``` erb
<% grid  = CandidatesGrid.new(followed: true) %>
<a href="<%= whatever_path(grid.param_name => grid.as_query) %>">Followed People</a>
```

**Comment by Ellerden** [comment]
Thanks! Works like a charm
