### ISSUE TITLE
Ajax enum/select filter

### ISSUE THREAD

**Issue by rbdmorgan** [bogdan/datagrid#295]
Is it possible to wire up a dynamic enum/select filter to something like this:

https://select2.org/data-sources/ajax

Would be useful when you have a proc/query that returns a lot of results.

**Comment by bogdan** [comment]
IMO providing endpoints to automatically load the options out of the box is doomed to have issues with different formats.
I wouldn't do it out of the box.

You can try something like this:

``` ruby
class MyGrid
  filter(:department, :string, input_options: {class: 'js-department-select'})
end

class DepartmentsSelectController
  def index
     render json: departments: Department.where("name like '%#{params[:q]}%'").limit(30).map {|d| {text: d.name, id: d.id}
  end
```

``` javascript
$('.js-department-select').select2({
  ajax: {
    url: 'https://api.github.com/search/repositories',
  }
});
```



```
