### ISSUE TITLE
add header to filter type enum or xboolean

### ISSUE THREAD

**Issue by mostafasobh** [bogdan/datagrid#302]
is it possible to have header for filter type enum?
if not is there away to add placeholder?

**Comment by bogdan** [comment]
You can add `placeholder` or any other HTML attribute this way:

```
filter(:category, :enum, input_options: {placeholder: "---Select---"})
```

I am not sure what do you mean by adding a header. Please explain.

**Comment by bogdan** [comment]
No followup - closing.
