### ISSUE TITLE
UI without HTML Table element

### ISSUE THREAD

**Issue by gap777** [bogdan/datagrid#310]
Hi,
Have you ever considered a UI that is not based on HTML Table for table-like data? HTML Tables are difficult to style, play by their own rules in CSS, and have rendering performance problems. I'm interested in a div-based solution to rendering my datagrid-based table data.

**Comment by bogdan** [comment]
Yes, there is a compatibility to modify HTML layout in the way you want.

Variant 1: modify built-in partials https://github.com/bogdan/datagrid/wiki/Frontend#modifying-built-in-partials
Variant 2: build custom layout like so https://github.com/bogdan/datagrid/wiki/Frontend#custom-table-layout

**Comment by bogdan** [comment]
No followup, closing.
