### ISSUE TITLE
Full HTML rendering context for empty state

### ISSUE THREAD

**Issue by gap777** [bogdan/datagrid#315]
By default, it seems that the table empty state must be a simple translated string:

```
/ _body.html.slim
- else
    tr
      td class="noresults" colspan="#{grid.html_columns.length}"  
        = I18n.t('datagrid.no_results')
```

We'd like to use richer HTML for the empty state, composed of images, links, etc, and generated by each table. 

```
/ _body.html.slim
- else
    tr
      td class="noresults" colspan="#{grid.html_columns.length}"  
        = grid.no_results_html
```

However, the `no_results_html` isn't being called from a view context (so we don't have access to helpers like `link_to`). 

How can we do this?

**Comment by bogdan** [comment]
Pass `self` into the `no_results_html`:

``` ruby
grid.no_results_html(self)
```

**Comment by gap777** [comment]
For posterity, I'll note that this appears to be something like a view context, and on it are all the helper methods I would expect and hope for:

```
def no_results_html(view_context)
    view_context.link_to ....
end
```

**Comment by bogdan** [comment]
Yes, it is. I just found there is another way:


```
class Grid
  include  Rails.application.routes.url_helper 
  def no_results_html
      helpers = ApplicationController.helpers
      helpers.content_tag(:div, "No Results") + helpers.link_to("Back", root_path) 
  end
end
```

Up to you....
