### ISSUE TITLE
Optimizing Single Authorization Check

### ISSUE THREAD

**Issue by MehmetCelik4** [bogdan/datagrid#318]
Hey,

Currently, the authorization check (can? method) is called repeatedly for each record in the grid, leading to performance concerns.

I'd like to optimize this by performing the authorization check just once and then applying it across all records. Any suggestions on how to best approach this.

Thanks in advance!

**Comment by bogdan** [comment]
Authorization check is not a part of datagrid. So,  please share your grid source code.

**Comment by MehmetCelik4** [comment]
thanks, man :), i figured it out
