### ISSUE TITLE
Unable to set class attribute for select filter

### ISSUE THREAD

**Issue by jkaufman** [bogdan/datagrid#319]
I am attempting to style the select filter using `input_options`. However, passing a value for `class` has no effect.

---

Declare a filter with input options specifying the class attribute:

`filter(:name, :enum, input_options: {class: 'border-gray-300'}, select: proc { …  })`

**Expected**

The provided value for `class` either combines with or clobbers the default value:

`<select class="border-gray-300" name="q[name]" id="q_name">`

**Actual**

The generated HTML retains the default value for `class`:
`<select class="name enum_filter" name="q[name]" id="q_name">`

**Comment by bogdan** [comment]
Fixed in 1.8.1. Please check.

**Comment by jkaufman** [comment]
Fix confirmed. The values are merged. Thank you!
