### ISSUE TITLE
User's current time zone

### ISSUE THREAD

**Issue by fzf** [bogdan/datagrid#320]
Great gem! I am loving playing around with it.

I am wondering if there is any way to inject the users current time zone similar to how https://github.com/basecamp/local_time works.

Thanks!

**Comment by fzf** [comment]
Nevermind. You can use the [html-columns](https://github.com/bogdan/datagrid/wiki/Columns#html-columns) solution to just pass in the local_time.

**Comment by bogdan** [comment]
I usually do some workarounds like:

``` ruby
time_column(:created_at)

def self.time_column(name, &block)
  column(name) do |model|
    format(block&.call || model.public_send(name)) do |value|
      local_time(value) # or any other helper
    end
  end
end
```

**Comment by fzf** [comment]
@bogdan yes, that is a much better pattern. Thank you!
