### ISSUE TITLE
Or filter

### ISSUE THREAD

**Issue by Mziserman** [bogdan/datagrid#322]
Hello, I want to have a filter that uses OR.

For example with a table users with first_name and last_name, I would want a way to get user with 
`SELECT * FROM users WHERE first_name = 'a' OR last_name = 'b'`

according to [the doc](https://github.com/bogdan/datagrid/wiki/Scope) this should be doable like

```ruby
@grid = UsersGrid.new(grid_params.slice(:first_name)) do |scope|
  scope
    .or(User.where(grid_params.slice(:last_name)))
    .page(params[:page])
end
```

but doing so does not use the or : 
<img width="1088" alt="image" src="https://github.com/bogdan/datagrid/assets/5013031/e5d41857-3013-4445-870f-30526ab9493c">

I also tried
```ruby
@grid.reset_scope
@grid.scope { User.where(grid_params.slice(:first_name)).or(User.where(grid_params.slice(:last_name))).page(params[:page]) }
````
with a similar result. Am I misunderstanding the doc ?

**Comment by bogdan** [comment]
That's a little tricky to achieve a single scope block for multiple filters.
I think the best way of doing it now is like this:

```
filter(:first_name, :string, dummy: true)
filter(:last_name, :string, allow_blank: true) do |scope, value, grid|
  scope.where("first_name = ? OR last_name = ?", grid.first_name, value)
end
```

That might seem counter intuitive to you, but I don't see a more elegant way of doing that.

**Comment by Mziserman** [comment]
Thanks a lot !
