### ISSUE TITLE
Grid for nested controllers

### ISSUE THREAD

**Issue by ka8725** [bogdan/datagrid#71]
Hi, your gem is really cool, but there is no one more feature which should be here in my opinion.
Imagine you have controller which serves nested route `/users/:user_id/tasks`:

``` ruby
class TasksController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @tasks = @user.tasks
  end
end
```

Currently I see how to do it but it seems as a hack:

``` ruby
class TasksController < ApplicationController
  def index
    @grid = TasksGrid.new((params[:tasks_grid] || {}).merge(:user_id => params[:user_id]))
    @assets = @grid.assets.paginate(:page => params[:page])
  end
end
```

I use your gem with [inherited_resources](https://github.com/josevalim/inherited_resources) and I'he created [mixin](https://gist.github.com/ka8725/6291592) which provides helpers for getting `@assets` and `@grid`.

But there is the same problem in this approach. I don't now may `datagrid` provides this ability but I've not find solution.

The best solution here I think will be in changing creation of grid object. For example:

``` ruby
@grid = TasksGrid.new(params[:tasks_grid], parent)
```

As you can see I suggest to pass scope as a second parameter.

**Comment by zsan** [comment]
Hello,

Just share

```
 @grid = TasksGrid.new((params[:tasks_grid] || {}).merge(:user_id => params[:user_id]))
```

Line code above will need `user_id` to be defined as a filter.

So maybe

```
def index
  @grid = TasksGrid.new(params[:tasks_grid])
  @grid.scope { @user.tasks }
end
```
