### ISSUE TITLE
Raise custom exception instead of NoMethodError when pass wrong parameters

### ISSUE THREAD

**Issue by palexvs** [bogdan/datagrid#89]
Raise custom exception (something like Datagrid::WrongParameters) instead of standard NoMethodError when pass wrong parameters to DataGrid.new().

**Comment by noahc** [comment]
rails/rails#10776 is merged. Does this need to be open anymore?

**Comment by theoros** [comment]
Maybe now it needs to be implemented.

**Comment by bogdan** [comment]
It is only available in Rails 5... while datagrid supports 4.x series still.

**Comment by theoros** [comment]
Do you think that functionality could be back-ported to Rails 4.x? Or that it would be a good idea to at least have it for Rails 5?

**Comment by bogdan** [comment]
> Do you think that functionality could be back-ported to Rails 4.x? 

Definitely not.

> Or that it would be a good idea to at least have it for Rails 5?

Yes, that's good idea.
